const txt = `Aries#male#Aries#male#reference#notes#88
Aries#male#Aries#female#reference#notes#88
Aries#female#Aries#female#reference#notes#88
Aries#male#Taurus#male#reference#notes#75
Aries#male#Taurus#female#reference#notes#75
Aries#female#Taurus#male#reference#notes#75
Aries#female#Taurus#female#reference#notes#75
Aries#male#Gemini#male#reference#notes#50
Aries#male#Gemini#female#reference#notes#50
Aries#female#Gemini#male#reference#notes#50
Aries#female#Gemini#female#reference#notes#50
Aries#male#Cancer#male#reference#notes#25
Aries#male#Cancer#female#reference#notes#25
Aries#female#Cancer#male#reference#notes#25
Aries#female#Cancer#female#reference#notes#25
Aries#male#Leo#male#reference#notes#88
Aries#male#Leo#female#reference#notes#88
Aries#female#Leo#male#reference#notes#88
Aries#female#Leo#female#reference#notes#88
Aries#male#Virgo#male#reference#notes#50
Aries#male#Virgo#female#reference#notes#50
Aries#female#Virgo#male#reference#notes#50
Aries#female#Virgo#female#reference#notes#50
Aries#male#Libra#male#reference#notes#50
Aries#male#Libra#female#reference#notes#50
Aries#female#Libra#male#reference#notes#50
Aries#female#Libra#female#reference#notes#50
Aries#male#Scorpius#male#reference#notes#25
Aries#male#Scorpius#female#reference#notes#25
Aries#female#Scorpius#male#reference#notes#25
Aries#female#Scorpius#female#reference#notes#25
Aries#male#사수#male#reference#notes#88
Aries#male#사수#female#reference#notes#88
Aries#female#사수#male#reference#notes#88
Aries#female#사수#female#reference#notes#88
Aries#male#Capricornus#male#reference#notes#38
Aries#male#Capricornus#female#reference#notes#38
Aries#female#Capricornus#male#reference#notes#38
Aries#female#Capricornus#female#reference#notes#38
Aries#male#Aquarius#male#reference#notes#50
Aries#male#Aquarius#female#reference#notes#50
Aries#female#Aquarius#male#reference#notes#50
Aries#female#Aquarius#female#reference#notes#50
Aries#male#Pisces#male#reference#notes#75
Aries#male#Pisces#female#reference#notes#75
Aries#female#Pisces#male#reference#notes#75
Aries#female#Pisces#female#reference#notes#75
Taurus#male#Taurus#male#reference#notes#88
Taurus#male#Taurus#female#reference#notes#88
Taurus#female#Taurus#female#reference#notes#88
Taurus#male#Gemini#male#reference#notes#13
Taurus#male#Gemini#female#reference#notes#13
Taurus#female#Gemini#male#reference#notes#13
Taurus#female#Gemini#female#reference#notes#13
Taurus#male#Cancer#male#reference#notes#50
Taurus#male#Cancer#female#reference#notes#50
Taurus#female#Cancer#male#reference#notes#50
Taurus#female#Cancer#female#reference#notes#50
Taurus#male#Leo#male#reference#notes#25
Taurus#male#Leo#female#reference#notes#25
Taurus#female#Leo#male#reference#notes#25
Taurus#female#Leo#female#reference#notes#25
Taurus#male#Virgo#male#reference#notes#100
Taurus#male#Virgo#female#reference#notes#100
Taurus#female#Virgo#male#reference#notes#100
Taurus#female#Virgo#female#reference#notes#100
Taurus#male#Libra#male#reference#notes#38
Taurus#male#Libra#female#reference#notes#38
Taurus#female#Libra#male#reference#notes#38
Taurus#female#Libra#female#reference#notes#38
Taurus#male#Scorpius#male#reference#notes#63
Taurus#male#Scorpius#female#reference#notes#63
Taurus#female#Scorpius#male#reference#notes#63
Taurus#female#Scorpius#female#reference#notes#63
Taurus#male#사수#male#reference#notes#75
Taurus#male#사수#female#reference#notes#75
Taurus#female#사수#male#reference#notes#75
Taurus#female#사수#female#reference#notes#75
Taurus#male#Capricornus#male#reference#notes#100
Taurus#male#Capricornus#female#reference#notes#100
Taurus#female#Capricornus#male#reference#notes#100
Taurus#female#Capricornus#female#reference#notes#100
Taurus#male#Aquarius#male#reference#notes#75
Taurus#male#Aquarius#female#reference#notes#75
Taurus#female#Aquarius#male#reference#notes#75
Taurus#female#Aquarius#female#reference#notes#75
Taurus#male#Pisces#male#reference#notes#50
Taurus#male#Pisces#female#reference#notes#50
Taurus#female#Pisces#male#reference#notes#50
Taurus#female#Pisces#female#reference#notes#50
Gemini#male#Gemini#male#reference#notes#88
Gemini#male#Gemini#female#reference#notes#88
Gemini#female#Gemini#female#reference#notes#88
Gemini#male#Cancer#male#reference#notes#75
Gemini#male#Cancer#female#reference#notes#75
Gemini#female#Cancer#male#reference#notes#75
Gemini#female#Cancer#female#reference#notes#75
Gemini#male#Leo#male#reference#notes#63
Gemini#male#Leo#female#reference#notes#63
Gemini#female#Leo#male#reference#notes#63
Gemini#female#Leo#female#reference#notes#63
Gemini#male#Virgo#male#reference#notes#75
Gemini#male#Virgo#female#reference#notes#75
Gemini#female#Virgo#male#reference#notes#75
Gemini#female#Virgo#female#reference#notes#75
Gemini#male#Libra#male#reference#notes#100
Gemini#male#Libra#female#reference#notes#100
Gemini#female#Libra#male#reference#notes#100
Gemini#female#Libra#female#reference#notes#100
Gemini#male#Scorpius#male#reference#notes#38
Gemini#male#Scorpius#female#reference#notes#38
Gemini#female#Scorpius#male#reference#notes#38
Gemini#female#Scorpius#female#reference#notes#38
Gemini#male#사수#male#reference#notes#63
Gemini#male#사수#female#reference#notes#63
Gemini#female#사수#male#reference#notes#63
Gemini#female#사수#female#reference#notes#63
Gemini#male#Capricornus#male#reference#notes#25
Gemini#male#Capricornus#female#reference#notes#25
Gemini#female#Capricornus#male#reference#notes#25
Gemini#female#Capricornus#female#reference#notes#25
Gemini#male#Aquarius#male#reference#notes#100
Gemini#male#Aquarius#female#reference#notes#100
Gemini#female#Aquarius#male#reference#notes#100
Gemini#female#Aquarius#female#reference#notes#100
Gemini#male#Pisces#male#reference#notes#75
Gemini#male#Pisces#female#reference#notes#75
Gemini#female#Pisces#male#reference#notes#75
Gemini#female#Pisces#female#reference#notes#75
Cancer#male#Cancer#male#reference#notes#88
Cancer#male#Cancer#female#reference#notes#88
Cancer#female#Cancer#female#reference#notes#88
Cancer#male#Leo#male#reference#notes#13
Cancer#male#Leo#female#reference#notes#13
Cancer#female#Leo#male#reference#notes#13
Cancer#female#Leo#female#reference#notes#13
Cancer#male#Virgo#male#reference#notes#63
Cancer#male#Virgo#female#reference#notes#63
Cancer#female#Virgo#male#reference#notes#63
Cancer#female#Virgo#female#reference#notes#63
Cancer#male#Libra#male#reference#notes#25
Cancer#male#Libra#female#reference#notes#25
Cancer#female#Libra#male#reference#notes#25
Cancer#female#Libra#female#reference#notes#25
Cancer#male#Scorpius#male#reference#notes#88
Cancer#male#Scorpius#female#reference#notes#88
Cancer#female#Scorpius#male#reference#notes#88
Cancer#female#Scorpius#female#reference#notes#88
Cancer#male#사수#male#reference#notes#13
Cancer#male#사수#female#reference#notes#13
Cancer#female#사수#male#reference#notes#13
Cancer#female#사수#female#reference#notes#13
Cancer#male#Capricornus#male#reference#notes#63
Cancer#male#Capricornus#female#reference#notes#63
Cancer#female#Capricornus#male#reference#notes#63
Cancer#female#Capricornus#female#reference#notes#63
Cancer#male#Aquarius#male#reference#notes#13
Cancer#male#Aquarius#female#reference#notes#13
Cancer#female#Aquarius#male#reference#notes#13
Cancer#female#Aquarius#female#reference#notes#13
Cancer#male#Pisces#male#reference#notes#100
Cancer#male#Pisces#female#reference#notes#100
Cancer#female#Pisces#male#reference#notes#100
Cancer#female#Pisces#female#reference#notes#100
Leo#male#Leo#male#reference#notes#100
Leo#male#Leo#female#reference#notes#100
Leo#female#Leo#female#reference#notes#100
Leo#male#Virgo#male#reference#notes#38
Leo#male#Virgo#female#reference#notes#38
Leo#female#Virgo#male#reference#notes#38
Leo#female#Virgo#female#reference#notes#38
Leo#male#Libra#male#reference#notes#50
Leo#male#Libra#female#reference#notes#50
Leo#female#Libra#male#reference#notes#50
Leo#female#Libra#female#reference#notes#50
Leo#male#Scorpius#male#reference#notes#75
Leo#male#Scorpius#female#reference#notes#75
Leo#female#Scorpius#male#reference#notes#75
Leo#female#Scorpius#female#reference#notes#75
Leo#male#사수#male#reference#notes#100
Leo#male#사수#female#reference#notes#100
Leo#female#사수#male#reference#notes#100
Leo#female#사수#female#reference#notes#100
Leo#male#Capricornus#male#reference#notes#50
Leo#male#Capricornus#female#reference#notes#50
Leo#female#Capricornus#male#reference#notes#50
Leo#female#Capricornus#female#reference#notes#50
Leo#male#Aquarius#male#reference#notes#50
Leo#male#Aquarius#female#reference#notes#50
Leo#female#Aquarius#male#reference#notes#50
Leo#female#Aquarius#female#reference#notes#50
Leo#male#Pisces#male#reference#notes#50
Leo#male#Pisces#female#reference#notes#50
Leo#female#Pisces#male#reference#notes#50
Leo#female#Pisces#female#reference#notes#50
Virgo#male#Virgo#male#reference#notes#88
Virgo#male#Virgo#female#reference#notes#88
Virgo#female#Virgo#female#reference#notes#88
Virgo#male#Libra#male#reference#notes#75
Virgo#male#Libra#female#reference#notes#75
Virgo#female#Libra#male#reference#notes#75
Virgo#female#Libra#female#reference#notes#75
Virgo#male#Scorpius#male#reference#notes#63
Virgo#male#Scorpius#female#reference#notes#63
Virgo#female#Scorpius#male#reference#notes#63
Virgo#female#Scorpius#female#reference#notes#63
Virgo#male#사수#male#reference#notes#38
Virgo#male#사수#female#reference#notes#38
Virgo#female#사수#male#reference#notes#38
Virgo#female#사수#female#reference#notes#38
Virgo#male#Capricornus#male#reference#notes#100
Virgo#male#Capricornus#female#reference#notes#100
Virgo#female#Capricornus#male#reference#notes#100
Virgo#female#Capricornus#female#reference#notes#100
Virgo#male#Aquarius#male#reference#notes#38
Virgo#male#Aquarius#female#reference#notes#38
Virgo#female#Aquarius#male#reference#notes#38
Virgo#female#Aquarius#female#reference#notes#38
Virgo#male#Pisces#male#reference#notes#25
Virgo#male#Pisces#female#reference#notes#25
Virgo#female#Pisces#male#reference#notes#25
Virgo#female#Pisces#female#reference#notes#25
Libra#male#Libra#male#reference#notes#100
Libra#male#Libra#female#reference#notes#100
Libra#female#Libra#female#reference#notes#100
Libra#male#Scorpius#male#reference#notes#75
Libra#male#Scorpius#female#reference#notes#75
Libra#female#Scorpius#male#reference#notes#75
Libra#female#Scorpius#female#reference#notes#63
Libra#male#사수#male#reference#notes#63
Libra#male#사수#female#reference#notes#63
Libra#female#사수#male#reference#notes#63
Libra#female#사수#female#reference#notes#63
Libra#male#Capricornus#male#reference#notes#25
Libra#male#Capricornus#female#reference#notes#25
Libra#female#Capricornus#male#reference#notes#25
Libra#female#Capricornus#female#reference#notes#25
Libra#male#Aquarius#male#reference#notes#88
Libra#male#Aquarius#female#reference#notes#88
Libra#female#Aquarius#male#reference#notes#88
Libra#female#Aquarius#female#reference#notes#88
Libra#male#Pisces#male#reference#notes#38
Libra#male#Pisces#female#reference#notes#38
Libra#female#Pisces#male#reference#notes#38
Libra#female#Pisces#female#reference#notes#38
Scorpius#male#Scorpius#male#reference#notes#88
Scorpius#male#Scorpius#female#reference#notes#88
Scorpius#female#Scorpius#female#reference#notes#88
Scorpius#male#사수#male#reference#notes#13
Scorpius#male#사수#female#reference#notes#13
Scorpius#female#사수#male#reference#notes#13
Scorpius#female#사수#female#reference#notes#13
Scorpius#male#Capricornus#male#reference#notes#50
Scorpius#male#Capricornus#female#reference#notes#50
Scorpius#female#Capricornus#male#reference#notes#50
Scorpius#female#Capricornus#female#reference#notes#50
Scorpius#male#Aquarius#male#reference#notes#75
Scorpius#male#Aquarius#female#reference#notes#75
Scorpius#female#Aquarius#male#reference#notes#75
Scorpius#female#Aquarius#female#reference#notes#75
Scorpius#male#Pisces#male#reference#notes#88
Scorpius#male#Pisces#female#reference#notes#88
Scorpius#female#Pisces#male#reference#notes#88
Scorpius#female#Pisces#female#reference#notes#88
사수#male#사수#male#reference#notes#88
사수#male#사수#female#reference#notes#88
사수#female#사수#female#reference#notes#88
사수#male#Capricornus#male#reference#notes#75
사수#male#Capricornus#female#reference#notes#75
사수#female#Capricornus#male#reference#notes#75
사수#female#Capricornus#female#reference#notes#75
사수#male#Aquarius#male#reference#notes#63
사수#male#Aquarius#female#reference#notes#63
사수#female#Aquarius#male#reference#notes#63
사수#female#Aquarius#female#reference#notes#63
사수#male#Pisces#male#reference#notes#38
사수#male#Pisces#female#reference#notes#38
사수#female#Pisces#male#reference#notes#38
사수#female#Pisces#female#reference#notes#38
Capricornus#male#Capricornus#male#reference#notes#88
Capricornus#male#Capricornus#female#reference#notes#88
Capricornus#female#Capricornus#female#reference#notes#88
Capricornus#male#Aquarius#male#reference#notes#25
Capricornus#male#Aquarius#female#reference#notes#25
Capricornus#female#Aquarius#male#reference#notes#25
Capricornus#female#Aquarius#female#reference#notes#25
Capricornus#male#Pisces#male#reference#notes#50
Capricornus#male#Pisces#female#reference#notes#50
Capricornus#female#Pisces#male#reference#notes#50
Capricornus#female#Pisces#female#reference#notes#50
Aquarius#male#Aquarius#male#reference#notes#100
Aquarius#male#Aquarius#female#reference#notes#100
Aquarius#female#Aquarius#female#reference#notes#100
Aquarius#male#Pisces#male#reference#notes#13
Aquarius#male#Pisces#female#reference#notes#13
Aquarius#female#Pisces#male#reference#notes#13
Aquarius#female#Pisces#female#reference#notes#13
Pisces#male#Pisces#male#reference#notes#88
Pisces#male#Pisces#female#reference#notes#88
Pisces#female#Pisces#female#reference#notes#88`;

export default txt;