const txt = `INTJ#male#INTJ#male#reference#notes#80
INTJ#male#INTJ#female#reference#notes#80
INTJ#female#INTJ#female#reference#notes#80
INTJ#male#INTP#male#reference#notes#80
INTJ#male#INTP#female#reference#notes#80
INTJ#female#INTP#male#reference#notes#80
INTJ#female#INTP#female#reference#notes#80
INTJ#male#ENTJ#male#reference#notes#80
INTJ#male#ENTJ#female#reference#notes#80
INTJ#female#ENTJ#male#reference#notes#80
INTJ#female#ENTJ#female#reference#notes#80
INTJ#male#ENTP#male#reference#notes#100
INTJ#male#ENTP#female#reference#notes#100
INTJ#female#ENTP#male#reference#notes#100
INTJ#female#ENTP#female#reference#notes#100
INTJ#male#INFJ#male#reference#notes#80
INTJ#male#INFJ#female#reference#notes#80
INTJ#female#INFJ#male#reference#notes#80
INTJ#female#INFJ#female#reference#notes#80
INTJ#male#INFP#male#reference#notes#80
INTJ#male#INFP#female#reference#notes#80
INTJ#female#INFP#male#reference#notes#80
INTJ#female#INFP#female#reference#notes#80
INTJ#male#ENFJ#male#reference#notes#80
INTJ#male#ENFJ#female#reference#notes#80
INTJ#female#ENFJ#male#reference#notes#80
INTJ#female#ENFJ#female#reference#notes#80
INTJ#male#ENFP#male#reference#notes#100
INTJ#male#ENFP#female#reference#notes#100
INTJ#female#ENFP#male#reference#notes#100
INTJ#female#ENFP#female#reference#notes#100
INTJ#male#ISTJ#male#reference#notes#40
INTJ#male#ISTJ#female#reference#notes#40
INTJ#female#ISTJ#male#reference#notes#40
INTJ#female#ISTJ#female#reference#notes#40
INTJ#male#ISFJ#male#reference#notes#40
INTJ#male#ISFJ#female#reference#notes#40
INTJ#female#ISFJ#male#reference#notes#40
INTJ#female#ISFJ#female#reference#notes#40
INTJ#male#ESTJ#male#reference#notes#40
INTJ#male#ESTJ#female#reference#notes#40
INTJ#female#ESTJ#male#reference#notes#40
INTJ#female#ESTJ#female#reference#notes#40
INTJ#male#ESFJ#male#reference#notes#40
INTJ#male#ESFJ#female#reference#notes#40
INTJ#female#ESFJ#male#reference#notes#40
INTJ#female#ESFJ#female#reference#notes#40
INTJ#male#ISTP#male#reference#notes#60
INTJ#male#ISTP#female#reference#notes#60
INTJ#female#ISTP#male#reference#notes#60
INTJ#female#ISTP#female#reference#notes#60
INTJ#male#ISFP#male#reference#notes#60
INTJ#male#ISFP#female#reference#notes#60
INTJ#female#ISFP#male#reference#notes#60
INTJ#female#ISFP#female#reference#notes#60
INTJ#male#ESTP#male#reference#notes#60
INTJ#male#ESTP#female#reference#notes#60
INTJ#female#ESTP#male#reference#notes#60
INTJ#female#ESTP#female#reference#notes#60
INTJ#male#ESFP#male#reference#notes#60
INTJ#male#ESFP#female#reference#notes#60
INTJ#female#ESFP#male#reference#notes#60
INTJ#female#ESFP#female#reference#notes#60
INTP#male#INTP#male#reference#notes#80
INTP#male#INTP#female#reference#notes#80
INTP#female#INTP#female#reference#notes#80
INTP#male#ENTJ#male#reference#notes#100
INTP#male#ENTJ#female#reference#notes#100
INTP#female#ENTJ#male#reference#notes#100
INTP#female#ENTJ#female#reference#notes#100
INTP#male#ENTP#male#reference#notes#80
INTP#male#ENTP#female#reference#notes#80
INTP#female#ENTP#male#reference#notes#80
INTP#female#ENTP#female#reference#notes#80
INTP#male#INFJ#male#reference#notes#80
INTP#male#INFJ#female#reference#notes#80
INTP#female#INFJ#male#reference#notes#80
INTP#female#INFJ#female#reference#notes#80
INTP#male#INFP#male#reference#notes#80
INTP#male#INFP#female#reference#notes#80
INTP#female#INFP#male#reference#notes#80
INTP#female#INFP#female#reference#notes#80
INTP#male#ENFJ#male#reference#notes#80
INTP#male#ENFJ#female#reference#notes#80
INTP#female#ENFJ#male#reference#notes#80
INTP#female#ENFJ#female#reference#notes#80
INTP#male#ENFP#male#reference#notes#80
INTP#male#ENFP#female#reference#notes#80
INTP#female#ENFP#male#reference#notes#80
INTP#female#ENFP#female#reference#notes#80
INTP#male#ISTJ#male#reference#notes#40
INTP#male#ISTJ#female#reference#notes#40
INTP#female#ISTJ#male#reference#notes#40
INTP#female#ISTJ#female#reference#notes#40
INTP#male#ISFJ#male#reference#notes#40
INTP#male#ISFJ#female#reference#notes#40
INTP#female#ISFJ#male#reference#notes#40
INTP#female#ISFJ#female#reference#notes#40
INTP#male#ESTJ#male#reference#notes#100
INTP#male#ESTJ#female#reference#notes#100
INTP#female#ESTJ#male#reference#notes#100
INTP#female#ESTJ#female#reference#notes#100
INTP#male#ESFJ#male#reference#notes#40
INTP#male#ESFJ#female#reference#notes#40
INTP#female#ESFJ#male#reference#notes#40
INTP#female#ESFJ#female#reference#notes#40
INTP#male#ISTP#male#reference#notes#60
INTP#male#ISTP#female#reference#notes#60
INTP#female#ISTP#male#reference#notes#60
INTP#female#ISTP#female#reference#notes#60
INTP#male#ISFP#male#reference#notes#60
INTP#male#ISFP#female#reference#notes#60
INTP#female#ISFP#male#reference#notes#60
INTP#female#ISFP#female#reference#notes#60
INTP#male#ESTP#male#reference#notes#60
INTP#male#ESTP#female#reference#notes#60
INTP#female#ESTP#male#reference#notes#60
INTP#female#ESTP#female#reference#notes#60
INTP#male#ESFP#male#reference#notes#60
INTP#male#ESFP#female#reference#notes#60
INTP#female#ESFP#male#reference#notes#60
INTP#female#ESFP#female#reference#notes#60
ENTJ#male#ENTJ#male#reference#notes#80
ENTJ#male#ENTJ#female#reference#notes#80
ENTJ#female#ENTJ#female#reference#notes#80
ENTJ#male#ENTP#male#reference#notes#80
ENTJ#male#ENTP#female#reference#notes#80
ENTJ#female#ENTP#male#reference#notes#80
ENTJ#female#ENTP#female#reference#notes#80
ENTJ#male#INFJ#male#reference#notes#80
ENTJ#male#INFJ#female#reference#notes#80
ENTJ#female#INFJ#male#reference#notes#80
ENTJ#female#INFJ#female#reference#notes#80
ENTJ#male#INFP#male#reference#notes#100
ENTJ#male#INFP#female#reference#notes#100
ENTJ#female#INFP#male#reference#notes#100
ENTJ#female#INFP#female#reference#notes#100
ENTJ#male#ENFJ#male#reference#notes#80
ENTJ#male#ENFJ#female#reference#notes#80
ENTJ#female#ENFJ#male#reference#notes#80
ENTJ#female#ENFJ#female#reference#notes#80
ENTJ#male#ENFP#male#reference#notes#80
ENTJ#male#ENFP#female#reference#notes#80
ENTJ#female#ENFP#male#reference#notes#80
ENTJ#female#ENFP#female#reference#notes#80
ENTJ#male#ISTJ#male#reference#notes#60
ENTJ#male#ISTJ#female#reference#notes#60
ENTJ#female#ISTJ#male#reference#notes#60
ENTJ#female#ISTJ#female#reference#notes#60
ENTJ#male#ISFJ#male#reference#notes#60
ENTJ#male#ISFJ#female#reference#notes#60
ENTJ#female#ISFJ#male#reference#notes#60
ENTJ#female#ISFJ#female#reference#notes#60
ENTJ#male#ESTJ#male#reference#notes#60
ENTJ#male#ESTJ#female#reference#notes#60
ENTJ#female#ESTJ#male#reference#notes#60
ENTJ#female#ESTJ#female#reference#notes#60
ENTJ#male#ESFJ#male#reference#notes#60
ENTJ#male#ESFJ#female#reference#notes#60
ENTJ#female#ESFJ#male#reference#notes#60
ENTJ#female#ESFJ#female#reference#notes#60
ENTJ#male#ISTP#male#reference#notes#60
ENTJ#male#ISTP#female#reference#notes#60
ENTJ#female#ISTP#male#reference#notes#60
ENTJ#female#ISTP#female#reference#notes#60
ENTJ#male#ISFP#male#reference#notes#60
ENTJ#male#ISFP#female#reference#notes#60
ENTJ#female#ISFP#male#reference#notes#60
ENTJ#female#ISFP#female#reference#notes#60
ENTJ#male#ESTP#male#reference#notes#60
ENTJ#male#ESTP#female#reference#notes#60
ENTJ#female#ESTP#male#reference#notes#60
ENTJ#female#ESTP#female#reference#notes#60
ENTJ#male#ESFP#male#reference#notes#60
ENTJ#male#ESFP#female#reference#notes#60
ENTJ#female#ESFP#male#reference#notes#60
ENTJ#female#ESFP#female#reference#notes#60
ENTP#male#ENTP#male#reference#notes#80
ENTP#male#ENTP#female#reference#notes#80
ENTP#female#ENTP#female#reference#notes#80
ENTP#male#INFJ#male#reference#notes#100
ENTP#male#INFJ#female#reference#notes#100
ENTP#female#INFJ#male#reference#notes#100
ENTP#female#INFJ#female#reference#notes#100
ENTP#male#INFP#male#reference#notes#80
ENTP#male#INFP#female#reference#notes#80
ENTP#female#INFP#male#reference#notes#80
ENTP#female#INFP#female#reference#notes#80
ENTP#male#ENFJ#male#reference#notes#80
ENTP#male#ENFJ#female#reference#notes#80
ENTP#female#ENFJ#male#reference#notes#80
ENTP#female#ENFJ#female#reference#notes#80
ENTP#male#ENFP#male#reference#notes#80
ENTP#male#ENFP#female#reference#notes#80
ENTP#female#ENFP#male#reference#notes#80
ENTP#female#ENFP#female#reference#notes#80
ENTP#male#ISTJ#male#reference#notes#40
ENTP#male#ISTJ#female#reference#notes#40
ENTP#female#ISTJ#male#reference#notes#40
ENTP#female#ISTJ#female#reference#notes#40
ENTP#male#ISFJ#male#reference#notes#40
ENTP#male#ISFJ#female#reference#notes#40
ENTP#female#ISFJ#male#reference#notes#40
ENTP#female#ISFJ#female#reference#notes#40
ENTP#male#ESTJ#male#reference#notes#40
ENTP#male#ESTJ#female#reference#notes#40
ENTP#female#ESTJ#male#reference#notes#40
ENTP#female#ESTJ#female#reference#notes#40
ENTP#male#ESFJ#male#reference#notes#40
ENTP#male#ESFJ#female#reference#notes#40
ENTP#female#ESFJ#male#reference#notes#40
ENTP#female#ESFJ#female#reference#notes#40
ENTP#male#ISTP#male#reference#notes#60
ENTP#male#ISTP#female#reference#notes#60
ENTP#female#ISTP#male#reference#notes#60
ENTP#female#ISTP#female#reference#notes#60
ENTP#male#ISFP#male#reference#notes#60
ENTP#male#ISFP#female#reference#notes#60
ENTP#female#ISFP#male#reference#notes#60
ENTP#female#ISFP#female#reference#notes#60
ENTP#male#ESTP#male#reference#notes#60
ENTP#male#ESTP#female#reference#notes#60
ENTP#female#ESTP#male#reference#notes#60
ENTP#female#ESTP#female#reference#notes#60
ENTP#male#ESFP#male#reference#notes#60
ENTP#male#ESFP#female#reference#notes#60
ENTP#female#ESFP#male#reference#notes#60
ENTP#female#ESFP#female#reference#notes#60
INFJ#male#INFJ#male#reference#notes#80
INFJ#male#INFJ#female#reference#notes#80
INFJ#female#INFJ#female#reference#notes#80
INFJ#male#INFP#male#reference#notes#80
INFJ#male#INFP#female#reference#notes#80
INFJ#female#INFP#male#reference#notes#80
INFJ#female#INFP#female#reference#notes#80
INFJ#male#ENFJ#male#reference#notes#80
INFJ#male#ENFJ#female#reference#notes#80
INFJ#female#ENFJ#male#reference#notes#80
INFJ#female#ENFJ#female#reference#notes#80
INFJ#male#ENFP#male#reference#notes#100
INFJ#male#ENFP#female#reference#notes#100
INFJ#female#ENFP#male#reference#notes#100
INFJ#female#ENFP#female#reference#notes#100
INFJ#male#ISTJ#male#reference#notes#20
INFJ#male#ISTJ#female#reference#notes#20
INFJ#female#ISTJ#male#reference#notes#20
INFJ#female#ISTJ#female#reference#notes#20
INFJ#male#ISFJ#male#reference#notes#20
INFJ#male#ISFJ#female#reference#notes#20
INFJ#female#ISFJ#male#reference#notes#20
INFJ#female#ISFJ#female#reference#notes#20
INFJ#male#ESTJ#male#reference#notes#20
INFJ#male#ESTJ#female#reference#notes#20
INFJ#female#ESTJ#male#reference#notes#20
INFJ#female#ESTJ#female#reference#notes#20
INFJ#male#ESFJ#male#reference#notes#20
INFJ#male#ESFJ#female#reference#notes#20
INFJ#female#ESFJ#male#reference#notes#20
INFJ#female#ESFJ#female#reference#notes#20
INFJ#male#ISTP#male#reference#notes#20
INFJ#male#ISTP#female#reference#notes#20
INFJ#female#ISTP#male#reference#notes#20
INFJ#female#ISTP#female#reference#notes#20
INFJ#male#ISFP#male#reference#notes#20
INFJ#male#ISFP#female#reference#notes#20
INFJ#female#ISFP#male#reference#notes#20
INFJ#female#ISFP#female#reference#notes#20
INFJ#male#ESTP#male#reference#notes#20
INFJ#male#ESTP#female#reference#notes#20
INFJ#female#ESTP#male#reference#notes#20
INFJ#female#ESTP#female#reference#notes#20
INFJ#male#ESFP#male#reference#notes#20
INFJ#male#ESFP#female#reference#notes#20
INFJ#female#ESFP#male#reference#notes#20
INFJ#female#ESFP#female#reference#notes#20
INFP#male#INFP#male#reference#notes#80
INFP#male#INFP#female#reference#notes#80
INFP#female#INFP#female#reference#notes#80
INFP#male#ENFJ#male#reference#notes#100
INFP#male#ENFJ#female#reference#notes#100
INFP#female#ENFJ#male#reference#notes#100
INFP#female#ENFJ#female#reference#notes#100
INFP#male#ENFP#male#reference#notes#80
INFP#male#ENFP#female#reference#notes#80
INFP#female#ENFP#male#reference#notes#80
INFP#female#ENFP#female#reference#notes#80
INFP#male#ISTJ#male#reference#notes#20
INFP#male#ISTJ#female#reference#notes#20
INFP#female#ISTJ#male#reference#notes#20
INFP#female#ISTJ#female#reference#notes#20
INFP#male#ISFJ#male#reference#notes#20
INFP#male#ISFJ#female#reference#notes#20
INFP#female#ISFJ#male#reference#notes#20
INFP#female#ISFJ#female#reference#notes#20
INFP#male#ESTJ#male#reference#notes#20
INFP#male#ESTJ#female#reference#notes#20
INFP#female#ESTJ#male#reference#notes#20
INFP#female#ESTJ#female#reference#notes#20
INFP#male#ESFJ#male#reference#notes#20
INFP#male#ESFJ#female#reference#notes#20
INFP#female#ESFJ#male#reference#notes#20
INFP#female#ESFJ#female#reference#notes#20
INFP#male#ISTP#male#reference#notes#20
INFP#male#ISTP#female#reference#notes#20
INFP#female#ISTP#male#reference#notes#20
INFP#female#ISTP#female#reference#notes#20
INFP#male#ISFP#male#reference#notes#20
INFP#male#ISFP#female#reference#notes#20
INFP#female#ISFP#male#reference#notes#20
INFP#female#ISFP#female#reference#notes#20
INFP#male#ESTP#male#reference#notes#20
INFP#male#ESTP#female#reference#notes#20
INFP#female#ESTP#male#reference#notes#20
INFP#female#ESTP#female#reference#notes#20
INFP#male#ESFP#male#reference#notes#20
INFP#male#ESFP#female#reference#notes#20
INFP#female#ESFP#male#reference#notes#20
INFP#female#ESFP#female#reference#notes#20
ENFJ#male#ENFJ#male#reference#notes#80
ENFJ#male#ENFJ#female#reference#notes#80
ENFJ#female#ENFJ#female#reference#notes#80
ENFJ#male#ENFP#male#reference#notes#80
ENFJ#male#ENFP#female#reference#notes#80
ENFJ#female#ENFP#male#reference#notes#80
ENFJ#female#ENFP#female#reference#notes#80
ENFJ#male#ISTJ#male#reference#notes#20
ENFJ#male#ISTJ#female#reference#notes#20
ENFJ#female#ISTJ#male#reference#notes#20
ENFJ#female#ISTJ#female#reference#notes#20
ENFJ#male#ISFJ#male#reference#notes#20
ENFJ#male#ISFJ#female#reference#notes#20
ENFJ#female#ISFJ#male#reference#notes#20
ENFJ#female#ISFJ#female#reference#notes#20
ENFJ#male#ESTJ#male#reference#notes#20
ENFJ#male#ESTJ#female#reference#notes#20
ENFJ#female#ESTJ#male#reference#notes#20
ENFJ#female#ESTJ#female#reference#notes#20
ENFJ#male#ESFJ#male#reference#notes#20
ENFJ#male#ESFJ#female#reference#notes#20
ENFJ#female#ESFJ#male#reference#notes#20
ENFJ#female#ESFJ#female#reference#notes#20
ENFJ#male#ISTP#male#reference#notes#20
ENFJ#male#ISTP#female#reference#notes#20
ENFJ#female#ISTP#male#reference#notes#20
ENFJ#female#ISTP#female#reference#notes#20
ENFJ#male#ISFP#male#reference#notes#100
ENFJ#male#ISFP#female#reference#notes#100
ENFJ#female#ISFP#male#reference#notes#100
ENFJ#female#ISFP#female#reference#notes#100
ENFJ#male#ESTP#male#reference#notes#20
ENFJ#male#ESTP#female#reference#notes#20
ENFJ#female#ESTP#male#reference#notes#20
ENFJ#female#ESTP#female#reference#notes#20
ENFJ#male#ESFP#male#reference#notes#20
ENFJ#male#ESFP#female#reference#notes#20
ENFJ#female#ESFP#male#reference#notes#20
ENFJ#female#ESFP#female#reference#notes#20
ENFP#male#ENFP#male#reference#notes#80
ENFP#male#ENFP#female#reference#notes#80
ENFP#female#ENFP#female#reference#notes#80
ENFP#male#ISTJ#male#reference#notes#20
ENFP#male#ISTJ#female#reference#notes#20
ENFP#female#ISTJ#male#reference#notes#20
ENFP#female#ISTJ#female#reference#notes#20
ENFP#male#ISFJ#male#reference#notes#20
ENFP#male#ISFJ#female#reference#notes#20
ENFP#female#ISFJ#male#reference#notes#20
ENFP#female#ISFJ#female#reference#notes#20
ENFP#male#ESTJ#male#reference#notes#20
ENFP#male#ESTJ#female#reference#notes#20
ENFP#female#ESTJ#male#reference#notes#20
ENFP#female#ESTJ#female#reference#notes#20
ENFP#male#ESFJ#male#reference#notes#20
ENFP#male#ESFJ#female#reference#notes#20
ENFP#female#ESFJ#male#reference#notes#20
ENFP#female#ESFJ#female#reference#notes#20
ENFP#male#ISTP#male#reference#notes#20
ENFP#male#ISTP#female#reference#notes#20
ENFP#female#ISTP#male#reference#notes#20
ENFP#female#ISTP#female#reference#notes#20
ENFP#male#ISFP#male#reference#notes#20
ENFP#male#ISFP#female#reference#notes#20
ENFP#female#ISFP#male#reference#notes#20
ENFP#female#ISFP#female#reference#notes#20
ENFP#male#ESTP#male#reference#notes#20
ENFP#male#ESTP#female#reference#notes#20
ENFP#female#ESTP#male#reference#notes#20
ENFP#female#ESTP#female#reference#notes#20
ENFP#male#ESFP#male#reference#notes#20
ENFP#male#ESFP#female#reference#notes#20
ENFP#female#ESFP#male#reference#notes#20
ENFP#female#ESFP#female#reference#notes#20
ISTJ#male#ISTJ#male#reference#notes#80
ISTJ#male#ISTJ#female#reference#notes#80
ISTJ#female#ISTJ#female#reference#notes#80
ISTJ#male#ISFJ#male#reference#notes#80
ISTJ#male#ISFJ#female#reference#notes#80
ISTJ#female#ISFJ#male#reference#notes#80
ISTJ#female#ISFJ#female#reference#notes#80
ISTJ#male#ESTJ#male#reference#notes#80
ISTJ#male#ESTJ#female#reference#notes#80
ISTJ#female#ESTJ#male#reference#notes#80
ISTJ#female#ESTJ#female#reference#notes#80
ISTJ#male#ESFJ#male#reference#notes#80
ISTJ#male#ESFJ#female#reference#notes#80
ISTJ#female#ESFJ#male#reference#notes#80
ISTJ#female#ESFJ#female#reference#notes#80
ISTJ#male#ISTP#male#reference#notes#60
ISTJ#male#ISTP#female#reference#notes#60
ISTJ#female#ISTP#male#reference#notes#60
ISTJ#female#ISTP#female#reference#notes#60
ISTJ#male#ISFP#male#reference#notes#60
ISTJ#male#ISFP#female#reference#notes#60
ISTJ#female#ISFP#male#reference#notes#60
ISTJ#female#ISFP#female#reference#notes#60
ISTJ#male#ESTP#male#reference#notes#100
ISTJ#male#ESTP#female#reference#notes#100
ISTJ#female#ESTP#male#reference#notes#100
ISTJ#female#ESTP#female#reference#notes#100
ISTJ#male#ESFP#male#reference#notes#100
ISTJ#male#ESFP#female#reference#notes#100
ISTJ#female#ESFP#male#reference#notes#100
ISTJ#female#ESFP#female#reference#notes#100
ISFJ#male#ISFJ#male#reference#notes#80
ISFJ#male#ISFJ#female#reference#notes#80
ISFJ#female#ISFJ#female#reference#notes#80
ISFJ#male#ESTJ#male#reference#notes#80
ISFJ#male#ESTJ#female#reference#notes#80
ISFJ#female#ESTJ#male#reference#notes#80
ISFJ#female#ESTJ#female#reference#notes#80
ISFJ#male#ESFJ#male#reference#notes#80
ISFJ#male#ESFJ#female#reference#notes#80
ISFJ#female#ESFJ#male#reference#notes#80
ISFJ#female#ESFJ#female#reference#notes#80
ISFJ#male#ISTP#male#reference#notes#60
ISFJ#male#ISTP#female#reference#notes#60
ISFJ#female#ISTP#male#reference#notes#60
ISFJ#female#ISTP#female#reference#notes#60
ISFJ#male#ISFP#male#reference#notes#60
ISFJ#male#ISFP#female#reference#notes#60
ISFJ#female#ISFP#male#reference#notes#60
ISFJ#female#ISFP#female#reference#notes#60
ISFJ#male#ESTP#male#reference#notes#100
ISFJ#male#ESTP#female#reference#notes#100
ISFJ#female#ESTP#male#reference#notes#100
ISFJ#female#ESTP#female#reference#notes#100
ISFJ#male#ESFP#male#reference#notes#100
ISFJ#male#ESFP#female#reference#notes#100
ISFJ#female#ESFP#male#reference#notes#100
ISFJ#female#ESFP#female#reference#notes#100
ESTJ#male#ESTJ#male#reference#notes#80
ESTJ#male#ESTJ#female#reference#notes#80
ESTJ#female#ESTJ#female#reference#notes#80
ESTJ#male#ESFJ#male#reference#notes#80
ESTJ#male#ESFJ#female#reference#notes#80
ESTJ#female#ESFJ#male#reference#notes#80
ESTJ#female#ESFJ#female#reference#notes#80
ESTJ#male#ISTP#male#reference#notes#100
ESTJ#male#ISTP#female#reference#notes#100
ESTJ#female#ISTP#male#reference#notes#100
ESTJ#female#ISTP#female#reference#notes#100
ESTJ#male#ISFP#male#reference#notes#100
ESTJ#male#ISFP#female#reference#notes#100
ESTJ#female#ISFP#male#reference#notes#100
ESTJ#female#ISFP#female#reference#notes#100
ESTJ#male#ESTP#male#reference#notes#60
ESTJ#male#ESTP#female#reference#notes#60
ESTJ#female#ESTP#male#reference#notes#60
ESTJ#female#ESTP#female#reference#notes#60
ESTJ#male#ESFP#male#reference#notes#60
ESTJ#male#ESFP#female#reference#notes#60
ESTJ#female#ESFP#male#reference#notes#60
ESTJ#female#ESFP#female#reference#notes#60
ESFJ#male#ESFJ#male#reference#notes#80
ESFJ#male#ESFJ#female#reference#notes#80
ESFJ#female#ESFJ#female#reference#notes#80
ESFJ#male#ISTP#male#reference#notes#100
ESFJ#male#ISTP#female#reference#notes#100
ESFJ#female#ISTP#male#reference#notes#100
ESFJ#female#ISTP#female#reference#notes#100
ESFJ#male#ISFP#male#reference#notes#100
ESFJ#male#ISFP#female#reference#notes#100
ESFJ#female#ISFP#male#reference#notes#100
ESFJ#female#ISFP#female#reference#notes#100
ESFJ#male#ESTP#male#reference#notes#60
ESFJ#male#ESTP#female#reference#notes#60
ESFJ#female#ESTP#male#reference#notes#60
ESFJ#female#ESTP#female#reference#notes#60
ESFJ#male#ESFP#male#reference#notes#60
ESFJ#male#ESFP#female#reference#notes#60
ESFJ#female#ESFP#male#reference#notes#60
ESFJ#female#ESFP#female#reference#notes#60
ISTP#male#ISTP#male#reference#notes#40
ISTP#male#ISTP#female#reference#notes#40
ISTP#female#ISTP#female#reference#notes#40
ISTP#male#ISFP#male#reference#notes#40
ISTP#male#ISFP#female#reference#notes#40
ISTP#female#ISFP#male#reference#notes#40
ISTP#female#ISFP#female#reference#notes#40
ISTP#male#ESTP#male#reference#notes#40
ISTP#male#ESTP#female#reference#notes#40
ISTP#female#ESTP#male#reference#notes#40
ISTP#female#ESTP#female#reference#notes#40
ISTP#male#ESFP#male#reference#notes#40
ISTP#male#ESFP#female#reference#notes#40
ISTP#female#ESFP#male#reference#notes#40
ISTP#female#ESFP#female#reference#notes#40
ISFP#male#ISFP#male#reference#notes#40
ISFP#male#ISFP#female#reference#notes#40
ISFP#female#ISFP#female#reference#notes#40
ISFP#male#ESTP#male#reference#notes#40
ISFP#male#ESTP#female#reference#notes#40
ISFP#female#ESTP#male#reference#notes#40
ISFP#female#ESTP#female#reference#notes#40
ISFP#male#ESFP#male#reference#notes#40
ISFP#male#ESFP#female#reference#notes#40
ISFP#female#ESFP#male#reference#notes#40
ISFP#female#ESFP#female#reference#notes#40
ESTP#male#ESTP#male#reference#notes#40
ESTP#male#ESTP#female#reference#notes#40
ESTP#female#ESTP#female#reference#notes#40
ESTP#male#ESFP#male#reference#notes#40
ESTP#male#ESFP#female#reference#notes#40
ESTP#female#ESFP#male#reference#notes#40
ESTP#female#ESFP#female#reference#notes#40
ESFP#male#ESFP#male#reference#notes#40
ESFP#male#ESFP#female#reference#notes#40
ESFP#female#ESFP#female#reference#notes#40`

export default txt;
