const txt = `INTJ#female#ENTP#female#reference#notes#100
INTJ#male#INFJ#male#reference#notes#80
INTJ#male#INFJ#female#reference#notes#80
INTJ#female#INFJ#male#reference#notes#80
INTJ#female#INFJ#female#reference#notes#80
INTJ#male#INFP#male#reference#notes#80
INTJ#male#INFP#female#reference#notes#80
INTJ#female#INFP#male#reference#notes#80
INTJ#female#INFP#female#reference#notes#80
INTJ#male#ENFJ#male#reference#notes#80
INTJ#male#ENFJ#female#reference#notes#80
INTJ#female#ENFJ#male#reference#notes#80
INTJ#female#ENFJ#female#reference#notes#80
INTJ#male#ENFP#male#reference#notes#100
INTJ#male#ENFP#female#reference#notes#100
INTJ#female#ENFP#male#reference#notes#100
INTJ#female#ENFP#female#reference#notes#100
INTJ#male#ISTJ#male#reference#notes#40
INTJ#male#ISTJ#female#reference#notes#40
INTJ#female#ISTJ#male#reference#notes#40
INTJ#female#ISTJ#female#reference#notes#40
INTJ#male#ISFJ#male#reference#notes#40
INTJ#male#ISFJ#female#reference#notes#40
INTJ#female#ISFJ#male#reference#notes#40
INTJ#female#ISFJ#female#reference#notes#40
INTJ#male#ESTJ#male#reference#notes#40
INTJ#male#ESTJ#female#reference#notes#40
INTJ#female#ESTJ#male#reference#notes#40
INTJ#female#ESTJ#female#reference#notes#40
INTJ#male#ESFJ#male#reference#notes#40
INTJ#male#ESFJ#female#reference#notes#40
INTJ#female#ESFJ#male#reference#notes#40
INTJ#female#ESFJ#female#reference#notes#40
INTJ#male#ISTP#male#reference#notes#60
INTJ#male#ISTP#female#reference#notes#60
INTJ#female#ISTP#male#reference#notes#60
INTJ#female#ISTP#female#reference#notes#60
INTJ#male#ISFP#male#reference#notes#60
INTJ#male#ISFP#female#reference#notes#60
INTJ#female#ISFP#male#reference#notes#60
INTJ#female#ISFP#female#reference#notes#60
INTJ#male#ESTP#male#reference#notes#60
INTJ#male#ESTP#female#reference#notes#60
INTJ#female#ESTP#male#reference#notes#60
INTJ#female#ESTP#female#reference#notes#60
INTJ#male#ESFP#male#reference#notes#60
INTJ#male#ESFP#female#reference#notes#60
INTJ#female#ESFP#male#reference#notes#60
INTJ#female#ESFP#female#reference#notes#60
INTP#male#INTJ#male#reference#notes#80
INTP#male#INTJ#female#reference#notes#80
INTP#female#INTJ#male#reference#notes#80
INTP#female#INTJ#female#reference#notes#80
INTP#male#INTP#male#reference#notes#80
INTP#male#INTP#female#reference#notes#80
INTP#female#INTP#male#reference#notes#80
INTP#female#INTP#female#reference#notes#80
INTP#male#ENTJ#male#reference#notes#100
INTP#male#ENTJ#female#reference#notes#100
INTP#female#ENTJ#male#reference#notes#100
INTP#female#ENTJ#female#reference#notes#100
INTP#male#ENTP#male#reference#notes#80
INTP#male#ENTP#female#reference#notes#80
INTP#female#ENTP#male#reference#notes#80
INTP#female#ENTP#female#reference#notes#80
INTP#male#INFJ#male#reference#notes#80
INTP#male#INFJ#female#reference#notes#80
INTP#female#INFJ#male#reference#notes#80
INTP#female#INFJ#female#reference#notes#80
INTP#male#INFP#male#reference#notes#80
INTP#male#INFP#female#reference#notes#80
INTP#female#INFP#male#reference#notes#80
INTP#female#INFP#female#reference#notes#80
INTP#male#ENFJ#male#reference#notes#80
INTP#male#ENFJ#female#reference#notes#80
INTP#female#ENFJ#male#reference#notes#80
INTP#female#ENFJ#female#reference#notes#80
INTP#male#ENFP#male#reference#notes#80
INTP#male#ENFP#female#reference#notes#80
INTP#female#ENFP#male#reference#notes#80
INTP#female#ENFP#female#reference#notes#80
INTP#male#ISTJ#male#reference#notes#40
INTP#male#ISTJ#female#reference#notes#40
INTP#female#ISTJ#male#reference#notes#40
INTP#female#ISTJ#female#reference#notes#40
INTP#male#ISFJ#male#reference#notes#40
INTP#male#ISFJ#female#reference#notes#40
INTP#female#ISFJ#male#reference#notes#40
INTP#female#ISFJ#female#reference#notes#40
INTP#male#ESTJ#male#reference#notes#100
INTP#male#ESTJ#female#reference#notes#100
INTP#female#ESTJ#male#reference#notes#100
INTP#female#ESTJ#female#reference#notes#100
INTP#male#ESFJ#male#reference#notes#40
INTP#male#ESFJ#female#reference#notes#40
INTP#female#ESFJ#male#reference#notes#40
INTP#female#ESFJ#female#reference#notes#40
INTP#male#ISTP#male#reference#notes#60
INTP#male#ISTP#female#reference#notes#60
INTP#female#ISTP#male#reference#notes#60
INTP#female#ISTP#female#reference#notes#60
INTP#male#ISFP#male#reference#notes#60
INTP#male#ISFP#female#reference#notes#60
INTP#female#ISFP#male#reference#notes#60
INTP#female#ISFP#female#reference#notes#60
INTP#male#ESTP#male#reference#notes#60
INTP#male#ESTP#female#reference#notes#60
INTP#female#ESTP#male#reference#notes#60
INTP#female#ESTP#female#reference#notes#60
INTP#male#ESFP#male#reference#notes#60
INTP#male#ESFP#female#reference#notes#60
INTP#female#ESFP#male#reference#notes#60
INTP#female#ESFP#female#reference#notes#60
ENTJ#male#INTJ#male#reference#notes#80
ENTJ#male#INTJ#female#reference#notes#80
ENTJ#female#INTJ#male#reference#notes#80
ENTJ#female#INTJ#female#reference#notes#80
ENTJ#male#INTP#male#reference#notes#100
ENTJ#male#INTP#female#reference#notes#100
ENTJ#female#INTP#male#reference#notes#100
ENTJ#female#INTP#female#reference#notes#100
ENTJ#male#ENTJ#male#reference#notes#80
ENTJ#male#ENTJ#female#reference#notes#80
ENTJ#female#ENTJ#male#reference#notes#80
ENTJ#female#ENTJ#female#reference#notes#80
ENTJ#male#ENTP#male#reference#notes#80
ENTJ#male#ENTP#female#reference#notes#80
ENTJ#female#ENTP#male#reference#notes#80
ENTJ#female#ENTP#female#reference#notes#80
ENTJ#male#INFJ#male#reference#notes#80
ENTJ#male#INFJ#female#reference#notes#80
ENTJ#female#INFJ#male#reference#notes#80
ENTJ#female#INFJ#female#reference#notes#80
ENTJ#male#INFP#male#reference#notes#100
ENTJ#male#INFP#female#reference#notes#100
ENTJ#female#INFP#male#reference#notes#100
ENTJ#female#INFP#female#reference#notes#100
ENTJ#male#ENFJ#male#reference#notes#80
ENTJ#male#ENFJ#female#reference#notes#80
ENTJ#female#ENFJ#male#reference#notes#80
ENTJ#female#ENFJ#female#reference#notes#80
ENTJ#male#ENFP#male#reference#notes#80
ENTJ#male#ENFP#female#reference#notes#80
ENTJ#female#ENFP#male#reference#notes#80
ENTJ#female#ENFP#female#reference#notes#80
ENTJ#male#ISTJ#male#reference#notes#60
ENTJ#male#ISTJ#female#reference#notes#60
ENTJ#female#ISTJ#male#reference#notes#60
ENTJ#female#ISTJ#female#reference#notes#60
ENTJ#male#ISFJ#male#reference#notes#60
ENTJ#male#ISFJ#female#reference#notes#60
ENTJ#female#ISFJ#male#reference#notes#60
ENTJ#female#ISFJ#female#reference#notes#60
ENTJ#male#ESTJ#male#reference#notes#60
ENTJ#male#ESTJ#female#reference#notes#60
ENTJ#female#ESTJ#male#reference#notes#60
ENTJ#female#ESTJ#female#reference#notes#60
ENTJ#male#ESFJ#male#reference#notes#60
ENTJ#male#ESFJ#female#reference#notes#60
ENTJ#female#ESFJ#male#reference#notes#60
ENTJ#female#ESFJ#female#reference#notes#60
ENTJ#male#ISTP#male#reference#notes#60
ENTJ#male#ISTP#female#reference#notes#60
ENTJ#female#ISTP#male#reference#notes#60
ENTJ#female#ISTP#female#reference#notes#60
ENTJ#male#ISFP#male#reference#notes#60
ENTJ#male#ISFP#female#reference#notes#60
ENTJ#female#ISFP#male#reference#notes#60
ENTJ#female#ISFP#female#reference#notes#60
ENTJ#male#ESTP#male#reference#notes#60
ENTJ#male#ESTP#female#reference#notes#60
ENTJ#female#ESTP#male#reference#notes#60
ENTJ#female#ESTP#female#reference#notes#60
ENTJ#male#ESFP#male#reference#notes#60
ENTJ#male#ESFP#female#reference#notes#60
ENTJ#female#ESFP#male#reference#notes#60
ENTJ#female#ESFP#female#reference#notes#60
ENTP#male#INTJ#male#reference#notes#100
ENTP#male#INTJ#female#reference#notes#100
ENTP#female#INTJ#male#reference#notes#100
ENTP#female#INTJ#female#reference#notes#100
ENTP#male#INTP#male#reference#notes#80
ENTP#male#INTP#female#reference#notes#80
ENTP#female#INTP#male#reference#notes#80
ENTP#female#INTP#female#reference#notes#80
ENTP#male#ENTJ#male#reference#notes#80
ENTP#male#ENTJ#female#reference#notes#80
ENTP#female#ENTJ#male#reference#notes#80
ENTP#female#ENTJ#female#reference#notes#80
ENTP#male#ENTP#male#reference#notes#80
ENTP#male#ENTP#female#reference#notes#80
ENTP#female#ENTP#male#reference#notes#80
ENTP#female#ENTP#female#reference#notes#80
ENTP#male#INFJ#male#reference#notes#100
ENTP#male#INFJ#female#reference#notes#100
ENTP#female#INFJ#male#reference#notes#100
ENTP#female#INFJ#female#reference#notes#100
ENTP#male#INFP#male#reference#notes#80
ENTP#male#INFP#female#reference#notes#80
ENTP#female#INFP#male#reference#notes#80
ENTP#female#INFP#female#reference#notes#80
ENTP#male#ENFJ#male#reference#notes#80
ENTP#male#ENFJ#female#reference#notes#80
ENTP#female#ENFJ#male#reference#notes#80
ENTP#female#ENFJ#female#reference#notes#80
ENTP#male#ENFP#male#reference#notes#80
ENTP#male#ENFP#female#reference#notes#80
ENTP#female#ENFP#male#reference#notes#80
ENTP#female#ENFP#female#reference#notes#80
ENTP#male#ISTJ#male#reference#notes#40
ENTP#male#ISTJ#female#reference#notes#40
ENTP#female#ISTJ#male#reference#notes#40
ENTP#female#ISTJ#female#reference#notes#40
ENTP#male#ISFJ#male#reference#notes#40
ENTP#male#ISFJ#female#reference#notes#40
ENTP#female#ISFJ#male#reference#notes#40
ENTP#female#ISFJ#female#reference#notes#40
ENTP#male#ESTJ#male#reference#notes#40
ENTP#male#ESTJ#female#reference#notes#40
ENTP#female#ESTJ#male#reference#notes#40
ENTP#female#ESTJ#female#reference#notes#40
ENTP#male#ESFJ#male#reference#notes#40
ENTP#male#ESFJ#female#reference#notes#40
ENTP#female#ESFJ#male#reference#notes#40
ENTP#female#ESFJ#female#reference#notes#40
ENTP#male#ISTP#male#reference#notes#60
ENTP#male#ISTP#female#reference#notes#60
ENTP#female#ISTP#male#reference#notes#60
ENTP#female#ISTP#female#reference#notes#60
ENTP#male#ISFP#male#reference#notes#60
ENTP#male#ISFP#female#reference#notes#60
ENTP#female#ISFP#male#reference#notes#60
ENTP#female#ISFP#female#reference#notes#60
ENTP#male#ESTP#male#reference#notes#60
ENTP#male#ESTP#female#reference#notes#60
ENTP#female#ESTP#male#reference#notes#60
ENTP#female#ESTP#female#reference#notes#60
ENTP#male#ESFP#male#reference#notes#60
ENTP#male#ESFP#female#reference#notes#60
ENTP#female#ESFP#male#reference#notes#60
ENTP#female#ESFP#female#reference#notes#60
INFJ#male#INTJ#male#reference#notes#80
INFJ#male#INTJ#female#reference#notes#80
INFJ#female#INTJ#male#reference#notes#80
INFJ#female#INTJ#female#reference#notes#80
INFJ#male#INTP#male#reference#notes#80
INFJ#male#INTP#female#reference#notes#80
INFJ#female#INTP#male#reference#notes#80
INFJ#female#INTP#female#reference#notes#80
INFJ#male#ENTJ#male#reference#notes#80
INFJ#male#ENTJ#female#reference#notes#80
INFJ#female#ENTJ#male#reference#notes#80
INFJ#female#ENTJ#female#reference#notes#80
INFJ#male#ENTP#male#reference#notes#100
INFJ#male#ENTP#female#reference#notes#100
INFJ#female#ENTP#male#reference#notes#100
INFJ#female#ENTP#female#reference#notes#100
INFJ#male#INFJ#male#reference#notes#80
INFJ#male#INFJ#female#reference#notes#80
INFJ#female#INFJ#male#reference#notes#80
INFJ#female#INFJ#female#reference#notes#80
INFJ#male#INFP#male#reference#notes#80
INFJ#male#INFP#female#reference#notes#80
INFJ#female#INFP#male#reference#notes#80
INFJ#female#INFP#female#reference#notes#80
INFJ#male#ENFJ#male#reference#notes#80
INFJ#male#ENFJ#female#reference#notes#80
INFJ#female#ENFJ#male#reference#notes#80
INFJ#female#ENFJ#female#reference#notes#80
INFJ#male#ENFP#male#reference#notes#100
INFJ#male#ENFP#female#reference#notes#100
INFJ#female#ENFP#male#reference#notes#100
INFJ#female#ENFP#female#reference#notes#100
INFJ#male#ISTJ#male#reference#notes#20
INFJ#male#ISTJ#female#reference#notes#20
INFJ#female#ISTJ#male#reference#notes#20
INFJ#female#ISTJ#female#reference#notes#20
INFJ#male#ISFJ#male#reference#notes#20
INFJ#male#ISFJ#female#reference#notes#20
INFJ#female#ISFJ#male#reference#notes#20
INFJ#female#ISFJ#female#reference#notes#20
INFJ#male#ESTJ#male#reference#notes#20
INFJ#male#ESTJ#female#reference#notes#20
INFJ#female#ESTJ#male#reference#notes#20
INFJ#female#ESTJ#female#reference#notes#20
INFJ#male#ESFJ#male#reference#notes#20
INFJ#male#ESFJ#female#reference#notes#20
INFJ#female#ESFJ#male#reference#notes#20
INFJ#female#ESFJ#female#reference#notes#20
INFJ#male#ISTP#male#reference#notes#20
INFJ#male#ISTP#female#reference#notes#20
INFJ#female#ISTP#male#reference#notes#20
INFJ#female#ISTP#female#reference#notes#20
INFJ#male#ISFP#male#reference#notes#20
INFJ#male#ISFP#female#reference#notes#20
INFJ#female#ISFP#male#reference#notes#20
INFJ#female#ISFP#female#reference#notes#20
INFJ#male#ESTP#male#reference#notes#20
INFJ#male#ESTP#female#reference#notes#20
INFJ#female#ESTP#male#reference#notes#20
INFJ#female#ESTP#female#reference#notes#20
INFJ#male#ESFP#male#reference#notes#20
INFJ#male#ESFP#female#reference#notes#20
INFJ#female#ESFP#male#reference#notes#20
INFJ#female#ESFP#female#reference#notes#20
INFP#male#INTJ#male#reference#notes#80
INFP#male#INTJ#female#reference#notes#80
INFP#female#INTJ#male#reference#notes#80
INFP#female#INTJ#female#reference#notes#80
INFP#male#INTP#male#reference#notes#80
INFP#male#INTP#female#reference#notes#80
INFP#female#INTP#male#reference#notes#80
INFP#female#INTP#female#reference#notes#80
INFP#male#ENTJ#male#reference#notes#100
INFP#male#ENTJ#female#reference#notes#100
INFP#female#ENTJ#male#reference#notes#100
INFP#female#ENTJ#female#reference#notes#100
INFP#male#ENTP#male#reference#notes#80
INFP#male#ENTP#female#reference#notes#80
INFP#female#ENTP#male#reference#notes#80
INFP#female#ENTP#female#reference#notes#80
INFP#male#INFJ#male#reference#notes#80
INFP#male#INFJ#female#reference#notes#80
INFP#female#INFJ#male#reference#notes#80
INFP#female#INFJ#female#reference#notes#80
INFP#male#INFP#male#reference#notes#80
INFP#male#INFP#female#reference#notes#80
INFP#female#INFP#male#reference#notes#80
INFP#female#INFP#female#reference#notes#80
INFP#male#ENFJ#male#reference#notes#100
INFP#male#ENFJ#female#reference#notes#100
INFP#female#ENFJ#male#reference#notes#100
INFP#female#ENFJ#female#reference#notes#100
INFP#male#ENFP#male#reference#notes#80
INFP#male#ENFP#female#reference#notes#80
INFP#female#ENFP#male#reference#notes#80
INFP#female#ENFP#female#reference#notes#80
INFP#male#ISTJ#male#reference#notes#20
INFP#male#ISTJ#female#reference#notes#20
INFP#female#ISTJ#male#reference#notes#20
INFP#female#ISTJ#female#reference#notes#20
INFP#male#ISFJ#male#reference#notes#20
INFP#male#ISFJ#female#reference#notes#20
INFP#female#ISFJ#male#reference#notes#20
INFP#female#ISFJ#female#reference#notes#20
INFP#male#ESTJ#male#reference#notes#20
INFP#male#ESTJ#female#reference#notes#20
INFP#female#ESTJ#male#reference#notes#20
INFP#female#ESTJ#female#reference#notes#20
INFP#male#ESFJ#male#reference#notes#20
INFP#male#ESFJ#female#reference#notes#20
INFP#female#ESFJ#male#reference#notes#20
INFP#female#ESFJ#female#reference#notes#20
INFP#male#ISTP#male#reference#notes#20
INFP#male#ISTP#female#reference#notes#20
INFP#female#ISTP#male#reference#notes#20
INFP#female#ISTP#female#reference#notes#20
INFP#male#ISFP#male#reference#notes#20
INFP#male#ISFP#female#reference#notes#20
INFP#female#ISFP#male#reference#notes#20
INFP#female#ISFP#female#reference#notes#20
INFP#male#ESTP#male#reference#notes#20
INFP#male#ESTP#female#reference#notes#20
INFP#female#ESTP#male#reference#notes#20
INFP#female#ESTP#female#reference#notes#20
INFP#male#ESFP#male#reference#notes#20
INFP#male#ESFP#female#reference#notes#20
INFP#female#ESFP#male#reference#notes#20
INFP#female#ESFP#female#reference#notes#20
ENFJ#male#INTJ#male#reference#notes#80
ENFJ#male#INTJ#female#reference#notes#80
ENFJ#female#INTJ#male#reference#notes#80
ENFJ#female#INTJ#female#reference#notes#80
ENFJ#male#INTP#male#reference#notes#80
ENFJ#male#INTP#female#reference#notes#80
ENFJ#female#INTP#male#reference#notes#80
ENFJ#female#INTP#female#reference#notes#80
ENFJ#male#ENTJ#male#reference#notes#80
ENFJ#male#ENTJ#female#reference#notes#80
ENFJ#female#ENTJ#male#reference#notes#80
ENFJ#female#ENTJ#female#reference#notes#80
ENFJ#male#ENTP#male#reference#notes#80
ENFJ#male#ENTP#female#reference#notes#80
ENFJ#female#ENTP#male#reference#notes#80
ENFJ#female#ENTP#female#reference#notes#80
ENFJ#male#INFJ#male#reference#notes#80
ENFJ#male#INFJ#female#reference#notes#80
ENFJ#female#INFJ#male#reference#notes#80
ENFJ#female#INFJ#female#reference#notes#80
ENFJ#male#INFP#male#reference#notes#100
ENFJ#male#INFP#female#reference#notes#100
ENFJ#female#INFP#male#reference#notes#100
ENFJ#female#INFP#female#reference#notes#100
ENFJ#male#ENFJ#male#reference#notes#80
ENFJ#male#ENFJ#female#reference#notes#80
ENFJ#female#ENFJ#male#reference#notes#80
ENFJ#female#ENFJ#female#reference#notes#80
ENFJ#male#ENFP#male#reference#notes#80
ENFJ#male#ENFP#female#reference#notes#80
ENFJ#female#ENFP#male#reference#notes#80
ENFJ#female#ENFP#female#reference#notes#80
ENFJ#male#ISTJ#male#reference#notes#20
ENFJ#male#ISTJ#female#reference#notes#20
ENFJ#female#ISTJ#male#reference#notes#20
ENFJ#female#ISTJ#female#reference#notes#20
ENFJ#male#ISFJ#male#reference#notes#20
ENFJ#male#ISFJ#female#reference#notes#20
ENFJ#female#ISFJ#male#reference#notes#20
ENFJ#female#ISFJ#female#reference#notes#20
ENFJ#male#ESTJ#male#reference#notes#20
ENFJ#male#ESTJ#female#reference#notes#20
ENFJ#female#ESTJ#male#reference#notes#20
ENFJ#female#ESTJ#female#reference#notes#20
ENFJ#male#ESFJ#male#reference#notes#20
ENFJ#male#ESFJ#female#reference#notes#20
ENFJ#female#ESFJ#male#reference#notes#20
ENFJ#female#ESFJ#female#reference#notes#20
ENFJ#male#ISTP#male#reference#notes#20
ENFJ#male#ISTP#female#reference#notes#20
ENFJ#female#ISTP#male#reference#notes#20
ENFJ#female#ISTP#female#reference#notes#20
ENFJ#male#ISFP#male#reference#notes#100
ENFJ#male#ISFP#female#reference#notes#100
ENFJ#female#ISFP#male#reference#notes#100
ENFJ#female#ISFP#female#reference#notes#100
ENFJ#male#ESTP#male#reference#notes#20
ENFJ#male#ESTP#female#reference#notes#20
ENFJ#female#ESTP#male#reference#notes#20
ENFJ#female#ESTP#female#reference#notes#20
ENFJ#male#ESFP#male#reference#notes#20
ENFJ#male#ESFP#female#reference#notes#20
ENFJ#female#ESFP#male#reference#notes#20
ENFJ#female#ESFP#female#reference#notes#20
ENFP#male#INTJ#male#reference#notes#100
ENFP#male#INTJ#female#reference#notes#100
ENFP#female#INTJ#male#reference#notes#100
ENFP#female#INTJ#female#reference#notes#100
ENFP#male#INTP#male#reference#notes#80
ENFP#male#INTP#female#reference#notes#80
ENFP#female#INTP#male#reference#notes#80
ENFP#female#INTP#female#reference#notes#80
ENFP#male#ENTJ#male#reference#notes#80
ENFP#male#ENTJ#female#reference#notes#80
ENFP#female#ENTJ#male#reference#notes#80
ENFP#female#ENTJ#female#reference#notes#80
ENFP#male#ENTP#male#reference#notes#80
ENFP#male#ENTP#female#reference#notes#80
ENFP#female#ENTP#male#reference#notes#80
ENFP#female#ENTP#female#reference#notes#80
ENFP#male#INFJ#male#reference#notes#100
ENFP#male#INFJ#female#reference#notes#100
ENFP#female#INFJ#male#reference#notes#100
ENFP#female#INFJ#female#reference#notes#100
ENFP#male#INFP#male#reference#notes#80
ENFP#male#INFP#female#reference#notes#80
ENFP#female#INFP#male#reference#notes#80
ENFP#female#INFP#female#reference#notes#80
ENFP#male#ENFJ#male#reference#notes#80
ENFP#male#ENFJ#female#reference#notes#80
ENFP#female#ENFJ#male#reference#notes#80
ENFP#female#ENFJ#female#reference#notes#80
ENFP#male#ENFP#male#reference#notes#80
ENFP#male#ENFP#female#reference#notes#80
ENFP#female#ENFP#male#reference#notes#80
ENFP#female#ENFP#female#reference#notes#80
ENFP#male#ISTJ#male#reference#notes#20
ENFP#male#ISTJ#female#reference#notes#20
ENFP#female#ISTJ#male#reference#notes#20
ENFP#female#ISTJ#female#reference#notes#20
ENFP#male#ISFJ#male#reference#notes#20
ENFP#male#ISFJ#female#reference#notes#20
ENFP#female#ISFJ#male#reference#notes#20
ENFP#female#ISFJ#female#reference#notes#20
ENFP#male#ESTJ#male#reference#notes#20
ENFP#male#ESTJ#female#reference#notes#20
ENFP#female#ESTJ#male#reference#notes#20
ENFP#female#ESTJ#female#reference#notes#20
ENFP#male#ESFJ#male#reference#notes#20
ENFP#male#ESFJ#female#reference#notes#20
ENFP#female#ESFJ#male#reference#notes#20
ENFP#female#ESFJ#female#reference#notes#20
ENFP#male#ISTP#male#reference#notes#20
ENFP#male#ISTP#female#reference#notes#20
ENFP#female#ISTP#male#reference#notes#20
ENFP#female#ISTP#female#reference#notes#20
ENFP#male#ISFP#male#reference#notes#20
ENFP#male#ISFP#female#reference#notes#20
ENFP#female#ISFP#male#reference#notes#20
ENFP#female#ISFP#female#reference#notes#20
ENFP#male#ESTP#male#reference#notes#20
ENFP#male#ESTP#female#reference#notes#20
ENFP#female#ESTP#male#reference#notes#20
ENFP#female#ESTP#female#reference#notes#20
ENFP#male#ESFP#male#reference#notes#20
ENFP#male#ESFP#female#reference#notes#20
ENFP#female#ESFP#male#reference#notes#20
ENFP#female#ESFP#female#reference#notes#20
ISTJ#male#INTJ#male#reference#notes#40
ISTJ#male#INTJ#female#reference#notes#40
ISTJ#female#INTJ#male#reference#notes#40
ISTJ#female#INTJ#female#reference#notes#40
ISTJ#male#INTP#male#reference#notes#40
ISTJ#male#INTP#female#reference#notes#40
ISTJ#female#INTP#male#reference#notes#40
ISTJ#female#INTP#female#reference#notes#40
ISTJ#male#ENTJ#male#reference#notes#60
ISTJ#male#ENTJ#female#reference#notes#60
ISTJ#female#ENTJ#male#reference#notes#60
ISTJ#female#ENTJ#female#reference#notes#60
ISTJ#male#ENTP#male#reference#notes#40
ISTJ#male#ENTP#female#reference#notes#40
ISTJ#female#ENTP#male#reference#notes#40
ISTJ#female#ENTP#female#reference#notes#40
ISTJ#male#INFJ#male#reference#notes#20
ISTJ#male#INFJ#female#reference#notes#20
ISTJ#female#INFJ#male#reference#notes#20
ISTJ#female#INFJ#female#reference#notes#20
ISTJ#male#INFP#male#reference#notes#20
ISTJ#male#INFP#female#reference#notes#20
ISTJ#female#INFP#male#reference#notes#20
ISTJ#female#INFP#female#reference#notes#20
ISTJ#male#ENFJ#male#reference#notes#20
ISTJ#male#ENFJ#female#reference#notes#20
ISTJ#female#ENFJ#male#reference#notes#20
ISTJ#female#ENFJ#female#reference#notes#20
ISTJ#male#ENFP#male#reference#notes#20
ISTJ#male#ENFP#female#reference#notes#20
ISTJ#female#ENFP#male#reference#notes#20
ISTJ#female#ENFP#female#reference#notes#20
ISTJ#male#ISTJ#male#reference#notes#80
ISTJ#male#ISTJ#female#reference#notes#80
ISTJ#female#ISTJ#male#reference#notes#80
ISTJ#female#ISTJ#female#reference#notes#80
ISTJ#male#ISFJ#male#reference#notes#80
ISTJ#male#ISFJ#female#reference#notes#80
ISTJ#female#ISFJ#male#reference#notes#80
ISTJ#female#ISFJ#female#reference#notes#80
ISTJ#male#ESTJ#male#reference#notes#80
ISTJ#male#ESTJ#female#reference#notes#80
ISTJ#female#ESTJ#male#reference#notes#80
ISTJ#female#ESTJ#female#reference#notes#80
ISTJ#male#ESFJ#male#reference#notes#80
ISTJ#male#ESFJ#female#reference#notes#80
ISTJ#female#ESFJ#male#reference#notes#80
ISTJ#female#ESFJ#female#reference#notes#80
ISTJ#male#ISTP#male#reference#notes#60
ISTJ#male#ISTP#female#reference#notes#60
ISTJ#female#ISTP#male#reference#notes#60
ISTJ#female#ISTP#female#reference#notes#60
ISTJ#male#ISFP#male#reference#notes#60
ISTJ#male#ISFP#female#reference#notes#60
ISTJ#female#ISFP#male#reference#notes#60
ISTJ#female#ISFP#female#reference#notes#60
ISTJ#male#ESTP#male#reference#notes#100
ISTJ#male#ESTP#female#reference#notes#100
ISTJ#female#ESTP#male#reference#notes#100
ISTJ#female#ESTP#female#reference#notes#100
ISTJ#male#ESFP#male#reference#notes#100
ISTJ#male#ESFP#female#reference#notes#100
ISTJ#female#ESFP#male#reference#notes#100
ISTJ#female#ESFP#female#reference#notes#100
ISFJ#male#INTJ#male#reference#notes#40
ISFJ#male#INTJ#female#reference#notes#40
ISFJ#female#INTJ#male#reference#notes#40
ISFJ#female#INTJ#female#reference#notes#40
ISFJ#male#INTP#male#reference#notes#40
ISFJ#male#INTP#female#reference#notes#40
ISFJ#female#INTP#male#reference#notes#40
ISFJ#female#INTP#female#reference#notes#40
ISFJ#male#ENTJ#male#reference#notes#60
ISFJ#male#ENTJ#female#reference#notes#60
ISFJ#female#ENTJ#male#reference#notes#60
ISFJ#female#ENTJ#female#reference#notes#60
ISFJ#male#ENTP#male#reference#notes#40
ISFJ#male#ENTP#female#reference#notes#40
ISFJ#female#ENTP#male#reference#notes#40
ISFJ#female#ENTP#female#reference#notes#40
ISFJ#male#INFJ#male#reference#notes#20
ISFJ#male#INFJ#female#reference#notes#20
ISFJ#female#INFJ#male#reference#notes#20
ISFJ#female#INFJ#female#reference#notes#20
ISFJ#male#INFP#male#reference#notes#20
ISFJ#male#INFP#female#reference#notes#20
ISFJ#female#INFP#male#reference#notes#20
ISFJ#female#INFP#female#reference#notes#20
ISFJ#male#ENFJ#male#reference#notes#20
ISFJ#male#ENFJ#female#reference#notes#20
ISFJ#female#ENFJ#male#reference#notes#20
ISFJ#female#ENFJ#female#reference#notes#20
ISFJ#male#ENFP#male#reference#notes#20
ISFJ#male#ENFP#female#reference#notes#20
ISFJ#female#ENFP#male#reference#notes#20
ISFJ#female#ENFP#female#reference#notes#20
ISFJ#male#ISTJ#male#reference#notes#80
ISFJ#male#ISTJ#female#reference#notes#80
ISFJ#female#ISTJ#male#reference#notes#80
ISFJ#female#ISTJ#female#reference#notes#80
ISFJ#male#ISFJ#male#reference#notes#80
ISFJ#male#ISFJ#female#reference#notes#80
ISFJ#female#ISFJ#male#reference#notes#80
ISFJ#female#ISFJ#female#reference#notes#80
ISFJ#male#ESTJ#male#reference#notes#80
ISFJ#male#ESTJ#female#reference#notes#80
ISFJ#female#ESTJ#male#reference#notes#80
ISFJ#female#ESTJ#female#reference#notes#80
ISFJ#male#ESFJ#male#reference#notes#80
ISFJ#male#ESFJ#female#reference#notes#80
ISFJ#female#ESFJ#male#reference#notes#80
ISFJ#female#ESFJ#female#reference#notes#80
ISFJ#male#ISTP#male#reference#notes#60
ISFJ#male#ISTP#female#reference#notes#60
ISFJ#female#ISTP#male#reference#notes#60
ISFJ#female#ISTP#female#reference#notes#60
ISFJ#male#ISFP#male#reference#notes#60
ISFJ#male#ISFP#female#reference#notes#60
ISFJ#female#ISFP#male#reference#notes#60
ISFJ#female#ISFP#female#reference#notes#60
ISFJ#male#ESTP#male#reference#notes#100
ISFJ#male#ESTP#female#reference#notes#100
ISFJ#female#ESTP#male#reference#notes#100
ISFJ#female#ESTP#female#reference#notes#100
ISFJ#male#ESFP#male#reference#notes#100
ISFJ#male#ESFP#female#reference#notes#100
ISFJ#female#ESFP#male#reference#notes#100
ISFJ#female#ESFP#female#reference#notes#100
ESTJ#male#INTJ#male#reference#notes#40
ESTJ#male#INTJ#female#reference#notes#40
ESTJ#female#INTJ#male#reference#notes#40
ESTJ#female#INTJ#female#reference#notes#40
ESTJ#male#INTP#male#reference#notes#100
ESTJ#male#INTP#female#reference#notes#100
ESTJ#female#INTP#male#reference#notes#100
ESTJ#female#INTP#female#reference#notes#100
ESTJ#male#ENTJ#male#reference#notes#60
ESTJ#male#ENTJ#female#reference#notes#60
ESTJ#female#ENTJ#male#reference#notes#60
ESTJ#female#ENTJ#female#reference#notes#60
ESTJ#male#ENTP#male#reference#notes#40
ESTJ#male#ENTP#female#reference#notes#40
ESTJ#female#ENTP#male#reference#notes#40
ESTJ#female#ENTP#female#reference#notes#40
ESTJ#male#INFJ#male#reference#notes#20
ESTJ#male#INFJ#female#reference#notes#20
ESTJ#female#INFJ#male#reference#notes#20
ESTJ#female#INFJ#female#reference#notes#20
ESTJ#male#INFP#male#reference#notes#20
ESTJ#male#INFP#female#reference#notes#20
ESTJ#female#INFP#male#reference#notes#20
ESTJ#female#INFP#female#reference#notes#20
ESTJ#male#ENFJ#male#reference#notes#20
ESTJ#male#ENFJ#female#reference#notes#20
ESTJ#female#ENFJ#male#reference#notes#20
ESTJ#female#ENFJ#female#reference#notes#20
ESTJ#male#ENFP#male#reference#notes#20
ESTJ#male#ENFP#female#reference#notes#20
ESTJ#female#ENFP#male#reference#notes#20
ESTJ#female#ENFP#female#reference#notes#20
ESTJ#male#ISTJ#male#reference#notes#80
ESTJ#male#ISTJ#female#reference#notes#80
ESTJ#female#ISTJ#male#reference#notes#80
ESTJ#female#ISTJ#female#reference#notes#80
ESTJ#male#ISFJ#male#reference#notes#80
ESTJ#male#ISFJ#female#reference#notes#80
ESTJ#female#ISFJ#male#reference#notes#80
ESTJ#female#ISFJ#female#reference#notes#80
ESTJ#male#ESTJ#male#reference#notes#80
ESTJ#male#ESTJ#female#reference#notes#80
ESTJ#female#ESTJ#male#reference#notes#80
ESTJ#female#ESTJ#female#reference#notes#80
ESTJ#male#ESFJ#male#reference#notes#80
ESTJ#male#ESFJ#female#reference#notes#80
ESTJ#female#ESFJ#male#reference#notes#80
ESTJ#female#ESFJ#female#reference#notes#80
ESTJ#male#ISTP#male#reference#notes#100
ESTJ#male#ISTP#female#reference#notes#100
ESTJ#female#ISTP#male#reference#notes#100
ESTJ#female#ISTP#female#reference#notes#100
ESTJ#male#ISFP#male#reference#notes#100
ESTJ#male#ISFP#female#reference#notes#100
ESTJ#female#ISFP#male#reference#notes#100
ESTJ#female#ISFP#female#reference#notes#100
ESTJ#male#ESTP#male#reference#notes#60
ESTJ#male#ESTP#female#reference#notes#60
ESTJ#female#ESTP#male#reference#notes#60
ESTJ#female#ESTP#female#reference#notes#60
ESTJ#male#ESFP#male#reference#notes#60
ESTJ#male#ESFP#female#reference#notes#60
ESTJ#female#ESFP#male#reference#notes#60
ESTJ#female#ESFP#female#reference#notes#60
ESFJ#male#INTJ#male#reference#notes#40
ESFJ#male#INTJ#female#reference#notes#40
ESFJ#female#INTJ#male#reference#notes#40
ESFJ#female#INTJ#female#reference#notes#40
ESFJ#male#INTP#male#reference#notes#40
ESFJ#male#INTP#female#reference#notes#40
ESFJ#female#INTP#male#reference#notes#40
ESFJ#female#INTP#female#reference#notes#40
ESFJ#male#ENTJ#male#reference#notes#60
ESFJ#male#ENTJ#female#reference#notes#60
ESFJ#female#ENTJ#male#reference#notes#60
ESFJ#female#ENTJ#female#reference#notes#60
ESFJ#male#ENTP#male#reference#notes#40
ESFJ#male#ENTP#female#reference#notes#40
ESFJ#female#ENTP#male#reference#notes#40
ESFJ#female#ENTP#female#reference#notes#40
ESFJ#male#INFJ#male#reference#notes#20
ESFJ#male#INFJ#female#reference#notes#20
ESFJ#female#INFJ#male#reference#notes#20
ESFJ#female#INFJ#female#reference#notes#20
ESFJ#male#INFP#male#reference#notes#20
ESFJ#male#INFP#female#reference#notes#20
ESFJ#female#INFP#male#reference#notes#20
ESFJ#female#INFP#female#reference#notes#20
ESFJ#male#ENFJ#male#reference#notes#20
ESFJ#male#ENFJ#female#reference#notes#20
ESFJ#female#ENFJ#male#reference#notes#20
ESFJ#female#ENFJ#female#reference#notes#20
ESFJ#male#ENFP#male#reference#notes#20
ESFJ#male#ENFP#female#reference#notes#20
ESFJ#female#ENFP#male#reference#notes#20
ESFJ#female#ENFP#female#reference#notes#20
ESFJ#male#ISTJ#male#reference#notes#80
ESFJ#male#ISTJ#female#reference#notes#80
ESFJ#female#ISTJ#male#reference#notes#80
ESFJ#female#ISTJ#female#reference#notes#80
ESFJ#male#ISFJ#male#reference#notes#80
ESFJ#male#ISFJ#female#reference#notes#80
ESFJ#female#ISFJ#male#reference#notes#80
ESFJ#female#ISFJ#female#reference#notes#80
ESFJ#male#ESTJ#male#reference#notes#80
ESFJ#male#ESTJ#female#reference#notes#80
ESFJ#female#ESTJ#male#reference#notes#80
ESFJ#female#ESTJ#female#reference#notes#80
ESFJ#male#ESFJ#male#reference#notes#80
ESFJ#male#ESFJ#female#reference#notes#80
ESFJ#female#ESFJ#male#reference#notes#80
ESFJ#female#ESFJ#female#reference#notes#80
ESFJ#male#ISTP#male#reference#notes#100
ESFJ#male#ISTP#female#reference#notes#100
ESFJ#female#ISTP#male#reference#notes#100
ESFJ#female#ISTP#female#reference#notes#100
ESFJ#male#ISFP#male#reference#notes#100
ESFJ#male#ISFP#female#reference#notes#100
ESFJ#female#ISFP#male#reference#notes#100
ESFJ#female#ISFP#female#reference#notes#100
ESFJ#male#ESTP#male#reference#notes#60
ESFJ#male#ESTP#female#reference#notes#60
ESFJ#female#ESTP#male#reference#notes#60
ESFJ#female#ESTP#female#reference#notes#60
ESFJ#male#ESFP#male#reference#notes#60
ESFJ#male#ESFP#female#reference#notes#60
ESFJ#female#ESFP#male#reference#notes#60
ESFJ#female#ESFP#female#reference#notes#60
ISTP#male#INTJ#male#reference#notes#60
ISTP#male#INTJ#female#reference#notes#60
ISTP#female#INTJ#male#reference#notes#60
ISTP#female#INTJ#female#reference#notes#60
ISTP#male#INTP#male#reference#notes#60
ISTP#male#INTP#female#reference#notes#60
ISTP#female#INTP#male#reference#notes#60
ISTP#female#INTP#female#reference#notes#60
ISTP#male#ENTJ#male#reference#notes#60
ISTP#male#ENTJ#female#reference#notes#60
ISTP#female#ENTJ#male#reference#notes#60
ISTP#female#ENTJ#female#reference#notes#60
ISTP#male#ENTP#male#reference#notes#60
ISTP#male#ENTP#female#reference#notes#60
ISTP#female#ENTP#male#reference#notes#60
ISTP#female#ENTP#female#reference#notes#60
ISTP#male#INFJ#male#reference#notes#20
ISTP#male#INFJ#female#reference#notes#20
ISTP#female#INFJ#male#reference#notes#20
ISTP#female#INFJ#female#reference#notes#20
ISTP#male#INFP#male#reference#notes#20
ISTP#male#INFP#female#reference#notes#20
ISTP#female#INFP#male#reference#notes#20
ISTP#female#INFP#female#reference#notes#20
ISTP#male#ENFJ#male#reference#notes#20
ISTP#male#ENFJ#female#reference#notes#20
ISTP#female#ENFJ#male#reference#notes#20
ISTP#female#ENFJ#female#reference#notes#20
ISTP#male#ENFP#male#reference#notes#20
ISTP#male#ENFP#female#reference#notes#20
ISTP#female#ENFP#male#reference#notes#20
ISTP#female#ENFP#female#reference#notes#20
ISTP#male#ISTJ#male#reference#notes#60
ISTP#male#ISTJ#female#reference#notes#60
ISTP#female#ISTJ#male#reference#notes#60
ISTP#female#ISTJ#female#reference#notes#60
ISTP#male#ISFJ#male#reference#notes#60
ISTP#male#ISFJ#female#reference#notes#60
ISTP#female#ISFJ#male#reference#notes#60
ISTP#female#ISFJ#female#reference#notes#60
ISTP#male#ESTJ#male#reference#notes#100
ISTP#male#ESTJ#female#reference#notes#100
ISTP#female#ESTJ#male#reference#notes#100
ISTP#female#ESTJ#female#reference#notes#100
ISTP#male#ESFJ#male#reference#notes#100
ISTP#male#ESFJ#female#reference#notes#100
ISTP#female#ESFJ#male#reference#notes#100
ISTP#female#ESFJ#female#reference#notes#100
ISTP#male#ISTP#male#reference#notes#40
ISTP#male#ISTP#female#reference#notes#40
ISTP#female#ISTP#male#reference#notes#40
ISTP#female#ISTP#female#reference#notes#40
ISTP#male#ISFP#male#reference#notes#40
ISTP#male#ISFP#female#reference#notes#40
ISTP#female#ISFP#male#reference#notes#40
ISTP#female#ISFP#female#reference#notes#40
ISTP#male#ESTP#male#reference#notes#40
ISTP#male#ESTP#female#reference#notes#40
ISTP#female#ESTP#male#reference#notes#40
ISTP#female#ESTP#female#reference#notes#40
ISTP#male#ESFP#male#reference#notes#40
ISTP#male#ESFP#female#reference#notes#40
ISTP#female#ESFP#male#reference#notes#40
ISTP#female#ESFP#female#reference#notes#40
ISFP#male#INTJ#male#reference#notes#60
ISFP#male#INTJ#female#reference#notes#60
ISFP#female#INTJ#male#reference#notes#60
ISFP#female#INTJ#female#reference#notes#60
ISFP#male#INTP#male#reference#notes#60
ISFP#male#INTP#female#reference#notes#60
ISFP#female#INTP#male#reference#notes#60
ISFP#female#INTP#female#reference#notes#60
ISFP#male#ENTJ#male#reference#notes#60
ISFP#male#ENTJ#female#reference#notes#60
ISFP#female#ENTJ#male#reference#notes#60
ISFP#female#ENTJ#female#reference#notes#60
ISFP#male#ENTP#male#reference#notes#0
ISFP#male#ENTP#female#reference#notes#0
ISFP#female#ENTP#male#reference#notes#0
ISFP#female#ENTP#female#reference#notes#0
ISFP#male#INFJ#male#reference#notes#20
ISFP#male#INFJ#female#reference#notes#20
ISFP#female#INFJ#male#reference#notes#20
ISFP#female#INFJ#female#reference#notes#20
ISFP#male#INFP#male#reference#notes#20
ISFP#male#INFP#female#reference#notes#20
ISFP#female#INFP#male#reference#notes#20
ISFP#female#INFP#female#reference#notes#20
ISFP#male#ENFJ#male#reference#notes#100
ISFP#male#ENFJ#female#reference#notes#100
ISFP#female#ENFJ#male#reference#notes#100
ISFP#female#ENFJ#female#reference#notes#100
ISFP#male#ENFP#male#reference#notes#20
ISFP#male#ENFP#female#reference#notes#20
ISFP#female#ENFP#male#reference#notes#20
ISFP#female#ENFP#female#reference#notes#20
ISFP#male#ISTJ#male#reference#notes#60
ISFP#male#ISTJ#female#reference#notes#60
ISFP#female#ISTJ#male#reference#notes#60
ISFP#female#ISTJ#female#reference#notes#60
ISFP#male#ISFJ#male#reference#notes#60
ISFP#male#ISFJ#female#reference#notes#60
ISFP#female#ISFJ#male#reference#notes#60
ISFP#female#ISFJ#female#reference#notes#60
ISFP#male#ESTJ#male#reference#notes#100
ISFP#male#ESTJ#female#reference#notes#100
ISFP#female#ESTJ#male#reference#notes#100
ISFP#female#ESTJ#female#reference#notes#100
ISFP#male#ESFJ#male#reference#notes#100
ISFP#male#ESFJ#female#reference#notes#100
ISFP#female#ESFJ#male#reference#notes#100
ISFP#female#ESFJ#female#reference#notes#100
ISFP#male#ISTP#male#reference#notes#40
ISFP#male#ISTP#female#reference#notes#40
ISFP#female#ISTP#male#reference#notes#40
ISFP#female#ISTP#female#reference#notes#40
ISFP#male#ISFP#male#reference#notes#40
ISFP#male#ISFP#female#reference#notes#40
ISFP#female#ISFP#male#reference#notes#40
ISFP#female#ISFP#female#reference#notes#40
ISFP#male#ESTP#male#reference#notes#40
ISFP#male#ESTP#female#reference#notes#40
ISFP#female#ESTP#male#reference#notes#40
ISFP#female#ESTP#female#reference#notes#40
ISFP#male#ESFP#male#reference#notes#40
ISFP#male#ESFP#female#reference#notes#40
ISFP#female#ESFP#male#reference#notes#40
ISFP#female#ESFP#female#reference#notes#40
ESTP#male#INTJ#male#reference#notes#60
ESTP#male#INTJ#female#reference#notes#60
ESTP#female#INTJ#male#reference#notes#60
ESTP#female#INTJ#female#reference#notes#60
ESTP#male#INTP#male#reference#notes#60
ESTP#male#INTP#female#reference#notes#60
ESTP#female#INTP#male#reference#notes#60
ESTP#female#INTP#female#reference#notes#60
ESTP#male#ENTJ#male#reference#notes#60
ESTP#male#ENTJ#female#reference#notes#60
ESTP#female#ENTJ#male#reference#notes#60
ESTP#female#ENTJ#female#reference#notes#60
ESTP#male#ENTP#male#reference#notes#60
ESTP#male#ENTP#female#reference#notes#60
ESTP#female#ENTP#male#reference#notes#60
ESTP#female#ENTP#female#reference#notes#60
ESTP#male#INFJ#male#reference#notes#20
ESTP#male#INFJ#female#reference#notes#20
ESTP#female#INFJ#male#reference#notes#20
ESTP#female#INFJ#female#reference#notes#20
ESTP#male#INFP#male#reference#notes#20
ESTP#male#INFP#female#reference#notes#20
ESTP#female#INFP#male#reference#notes#20
ESTP#female#INFP#female#reference#notes#20
ESTP#male#ENFJ#male#reference#notes#20
ESTP#male#ENFJ#female#reference#notes#20
ESTP#female#ENFJ#male#reference#notes#20
ESTP#female#ENFJ#female#reference#notes#20
ESTP#male#ENFP#male#reference#notes#20
ESTP#male#ENFP#female#reference#notes#20
ESTP#female#ENFP#male#reference#notes#20
ESTP#female#ENFP#female#reference#notes#20
ESTP#male#ISTJ#male#reference#notes#100
ESTP#male#ISTJ#female#reference#notes#100
ESTP#female#ISTJ#male#reference#notes#100
ESTP#female#ISTJ#female#reference#notes#100
ESTP#male#ISFJ#male#reference#notes#100
ESTP#male#ISFJ#female#reference#notes#100
ESTP#female#ISFJ#male#reference#notes#100
ESTP#female#ISFJ#female#reference#notes#100
ESTP#male#ESTJ#male#reference#notes#60
ESTP#male#ESTJ#female#reference#notes#60
ESTP#female#ESTJ#male#reference#notes#60
ESTP#female#ESTJ#female#reference#notes#60
ESTP#male#ESFJ#male#reference#notes#60
ESTP#male#ESFJ#female#reference#notes#60
ESTP#female#ESFJ#male#reference#notes#60
ESTP#female#ESFJ#female#reference#notes#60
ESTP#male#ISTP#male#reference#notes#40
ESTP#male#ISTP#female#reference#notes#40
ESTP#female#ISTP#male#reference#notes#40
ESTP#female#ISTP#female#reference#notes#40
ESTP#male#ISFP#male#reference#notes#40
ESTP#male#ISFP#female#reference#notes#40
ESTP#female#ISFP#male#reference#notes#40
ESTP#female#ISFP#female#reference#notes#40
ESTP#male#ESTP#male#reference#notes#40
ESTP#male#ESTP#female#reference#notes#40
ESTP#female#ESTP#male#reference#notes#40
ESTP#female#ESTP#female#reference#notes#40
ESTP#male#ESFP#male#reference#notes#40
ESTP#male#ESFP#female#reference#notes#40
ESTP#female#ESFP#male#reference#notes#40
ESTP#female#ESFP#female#reference#notes#40
ESFP#male#INTJ#male#reference#notes#60
ESFP#male#INTJ#female#reference#notes#60
ESFP#female#INTJ#male#reference#notes#60
ESFP#female#INTJ#female#reference#notes#60
ESFP#male#INTP#male#reference#notes#60
ESFP#male#INTP#female#reference#notes#60
ESFP#female#INTP#male#reference#notes#60
ESFP#female#INTP#female#reference#notes#60
ESFP#male#ENTJ#male#reference#notes#60
ESFP#male#ENTJ#female#reference#notes#60
ESFP#female#ENTJ#male#reference#notes#60
ESFP#female#ENTJ#female#reference#notes#60
ESFP#male#ENTP#male#reference#notes#60
ESFP#male#ENTP#female#reference#notes#60
ESFP#female#ENTP#male#reference#notes#60
ESFP#female#ENTP#female#reference#notes#60
ESFP#male#INFJ#male#reference#notes#20
ESFP#male#INFJ#female#reference#notes#20
ESFP#female#INFJ#male#reference#notes#20
ESFP#female#INFJ#female#reference#notes#20
ESFP#male#INFP#male#reference#notes#20
ESFP#male#INFP#female#reference#notes#20
ESFP#female#INFP#male#reference#notes#20
ESFP#female#INFP#female#reference#notes#20
ESFP#male#ENFJ#male#reference#notes#20
ESFP#male#ENFJ#female#reference#notes#20
ESFP#female#ENFJ#male#reference#notes#20
ESFP#female#ENFJ#female#reference#notes#20
ESFP#male#ENFP#male#reference#notes#20
ESFP#male#ENFP#female#reference#notes#20
ESFP#female#ENFP#male#reference#notes#20
ESFP#female#ENFP#female#reference#notes#20
ESFP#male#ISTJ#male#reference#notes#100
ESFP#male#ISTJ#female#reference#notes#100
ESFP#female#ISTJ#male#reference#notes#100
ESFP#female#ISTJ#female#reference#notes#100
ESFP#male#ISFJ#male#reference#notes#100
ESFP#male#ISFJ#female#reference#notes#100
ESFP#female#ISFJ#male#reference#notes#100
ESFP#female#ISFJ#female#reference#notes#100
ESFP#male#ESTJ#male#reference#notes#60
ESFP#male#ESTJ#female#reference#notes#60
ESFP#female#ESTJ#male#reference#notes#60
ESFP#female#ESTJ#female#reference#notes#60
ESFP#male#ESFJ#male#reference#notes#60
ESFP#male#ESFJ#female#reference#notes#60
ESFP#female#ESFJ#male#reference#notes#60
ESFP#female#ESFJ#female#reference#notes#60
ESFP#male#ISTP#male#reference#notes#40
ESFP#male#ISTP#female#reference#notes#40
ESFP#female#ISTP#male#reference#notes#40
ESFP#female#ISTP#female#reference#notes#40
ESFP#male#ISFP#male#reference#notes#40
ESFP#male#ISFP#female#reference#notes#40
ESFP#female#ISFP#male#reference#notes#40
ESFP#female#ISFP#female#reference#notes#40
ESFP#male#ESTP#male#reference#notes#40
ESFP#male#ESTP#female#reference#notes#40
ESFP#female#ESTP#male#reference#notes#40
ESFP#female#ESTP#female#reference#notes#40
ESFP#male#ESFP#male#reference#notes#40
ESFP#male#ESFP#female#reference#notes#40
ESFP#female#ESFP#male#reference#notes#40
ESFP#female#ESFP#female#reference#notes#40`;

export default txt;
