const txt = `mouse#male#mouse#male#reference#notes#75
mouse#male#mouse#female#reference#notes#75
mouse#female#mouse#female#reference#notes#75
mouse#male#ox#male#reference#notes#100
mouse#male#ox#female#reference#notes#100
mouse#female#ox#male#reference#notes#100
mouse#female#ox#female#reference#notes#100
mouse#male#tiger#male#reference#notes#75
mouse#male#tiger#female#reference#notes#75
mouse#female#tiger#male#reference#notes#75
mouse#female#tiger#female#reference#notes#75
mouse#male#rabbit#male#reference#notes#50
mouse#male#rabbit#female#reference#notes#50
mouse#female#rabbit#male#reference#notes#50
mouse#female#rabbit#female#reference#notes#50
mouse#male#dragon#male#reference#notes#100
mouse#male#dragon#female#reference#notes#100
mouse#female#dragon#male#reference#notes#100
mouse#female#dragon#female#reference#notes#100
mouse#male#snake#male#reference#notes#75
mouse#male#snake#female#reference#notes#75
mouse#female#snake#male#reference#notes#75
mouse#female#snake#female#reference#notes#75
mouse#male#horse#male#reference#notes#50
mouse#male#horse#female#reference#notes#50
mouse#female#horse#male#reference#notes#50
mouse#female#horse#female#reference#notes#50
mouse#male#lamb#male#reference#notes#50
mouse#male#lamb#female#reference#notes#50
mouse#female#lamb#male#reference#notes#50
mouse#female#lamb#female#reference#notes#50
mouse#male#monkey#male#reference#notes#100
mouse#male#monkey#female#reference#notes#100
mouse#female#monkey#male#reference#notes#100
mouse#female#monkey#female#reference#notes#100
mouse#male#rooster#male#reference#notes#50
mouse#male#rooster#female#reference#notes#50
mouse#female#rooster#male#reference#notes#50
mouse#female#rooster#female#reference#notes#50
mouse#male#dog#male#reference#notes#75
mouse#male#dog#female#reference#notes#75
mouse#female#dog#male#reference#notes#75
mouse#female#dog#female#reference#notes#75
mouse#male#pig#male#reference#notes#75
mouse#male#pig#female#reference#notes#75
mouse#female#pig#male#reference#notes#75
mouse#female#pig#female#reference#notes#75
ox#male#ox#male#reference#notes#75
ox#male#ox#female#reference#notes#75
ox#female#ox#female#reference#notes#75
ox#male#tiger#male#reference#notes#75
ox#male#tiger#female#reference#notes#75
ox#female#tiger#male#reference#notes#75
ox#female#tiger#female#reference#notes#75
ox#male#rabbit#male#reference#notes#75
ox#male#rabbit#female#reference#notes#75
ox#female#rabbit#male#reference#notes#75
ox#female#rabbit#female#reference#notes#75
ox#male#dragon#male#reference#notes#50
ox#male#dragon#female#reference#notes#50
ox#female#dragon#male#reference#notes#50
ox#female#dragon#female#reference#notes#50
ox#male#snake#male#reference#notes#100
ox#male#snake#female#reference#notes#100
ox#female#snake#male#reference#notes#100
ox#female#snake#female#reference#notes#100
ox#male#horse#male#reference#notes#50
ox#male#horse#female#reference#notes#50
ox#female#horse#male#reference#notes#50
ox#female#horse#female#reference#notes#50
ox#male#lamb#male#reference#notes#50
ox#male#lamb#female#reference#notes#50
ox#female#lamb#male#reference#notes#50
ox#female#lamb#female#reference#notes#50
ox#male#monkey#male#reference#notes#75
ox#male#monkey#female#reference#notes#75
ox#female#monkey#male#reference#notes#75
ox#female#monkey#female#reference#notes#75
ox#male#rooster#male#reference#notes#100
ox#male#rooster#female#reference#notes#100
ox#female#rooster#male#reference#notes#100
ox#female#rooster#female#reference#notes#100
ox#male#dog#male#reference#notes#50
ox#male#dog#female#reference#notes#50
ox#female#dog#male#reference#notes#50
ox#female#dog#female#reference#notes#50
ox#male#pig#male#reference#notes#75
ox#male#pig#female#reference#notes#75
ox#female#pig#male#reference#notes#75
ox#female#pig#female#reference#notes#75
tiger#male#tiger#male#reference#notes#75
tiger#male#tiger#female#reference#notes#75
tiger#female#tiger#female#reference#notes#75
tiger#male#rabbit#male#reference#notes#75
tiger#male#rabbit#female#reference#notes#75
tiger#female#rabbit#male#reference#notes#75
tiger#female#rabbit#female#reference#notes#75
tiger#male#dragon#male#reference#notes#75
tiger#male#dragon#female#reference#notes#75
tiger#female#dragon#male#reference#notes#75
tiger#female#dragon#female#reference#notes#75
tiger#male#snake#male#reference#notes#50
tiger#male#snake#female#reference#notes#50
tiger#female#snake#male#reference#notes#50
tiger#female#snake#female#reference#notes#50
tiger#male#horse#male#reference#notes#100
tiger#male#horse#female#reference#notes#100
tiger#female#horse#male#reference#notes#100
tiger#female#horse#female#reference#notes#100
tiger#male#lamb#male#reference#notes#75
tiger#male#lamb#female#reference#notes#75
tiger#female#lamb#male#reference#notes#75
tiger#female#lamb#female#reference#notes#75
tiger#male#monkey#male#reference#notes#50
tiger#male#monkey#female#reference#notes#50
tiger#female#monkey#male#reference#notes#50
tiger#female#monkey#female#reference#notes#50
tiger#male#rooster#male#reference#notes#50
tiger#male#rooster#female#reference#notes#50
tiger#female#rooster#male#reference#notes#50
tiger#female#rooster#female#reference#notes#50
tiger#male#dog#male#reference#notes#100
tiger#male#dog#female#reference#notes#100
tiger#female#dog#male#reference#notes#100
tiger#female#dog#female#reference#notes#100
tiger#male#pig#male#reference#notes#100
tiger#male#pig#female#reference#notes#100
tiger#female#pig#male#reference#notes#100
tiger#female#pig#female#reference#notes#100
rabbit#male#rabbit#male#reference#notes#75
rabbit#male#rabbit#female#reference#notes#75
rabbit#female#rabbit#female#reference#notes#75
rabbit#male#dragon#male#reference#notes#50
rabbit#male#dragon#female#reference#notes#50
rabbit#female#dragon#male#reference#notes#50
rabbit#female#dragon#female#reference#notes#50
rabbit#male#snake#male#reference#notes#75
rabbit#male#snake#female#reference#notes#75
rabbit#female#snake#male#reference#notes#75
rabbit#female#snake#female#reference#notes#75
rabbit#male#horse#male#reference#notes#50
rabbit#male#horse#female#reference#notes#50
rabbit#female#horse#male#reference#notes#50
rabbit#female#horse#female#reference#notes#50
rabbit#male#lamb#male#reference#notes#100
rabbit#male#lamb#female#reference#notes#100
rabbit#female#lamb#male#reference#notes#100
rabbit#female#lamb#female#reference#notes#100
rabbit#male#monkey#male#reference#notes#50
rabbit#male#monkey#female#reference#notes#50
rabbit#female#monkey#male#reference#notes#50
rabbit#female#monkey#female#reference#notes#50
rabbit#male#rooster#male#reference#notes#25
rabbit#male#rooster#female#reference#notes#25
rabbit#female#rooster#male#reference#notes#25
rabbit#female#rooster#female#reference#notes#25
rabbit#male#dog#male#reference#notes#100
rabbit#male#dog#female#reference#notes#100
rabbit#female#dog#male#reference#notes#100
rabbit#female#dog#female#reference#notes#100
rabbit#male#pig#male#reference#notes#100
rabbit#male#pig#female#reference#notes#100
rabbit#female#pig#male#reference#notes#100
rabbit#female#pig#female#reference#notes#100
dragon#male#dragon#male#reference#notes#50
dragon#male#dragon#female#reference#notes#50
dragon#female#dragon#female#reference#notes#50
dragon#male#snake#male#reference#notes#75
dragon#male#snake#female#reference#notes#75
dragon#female#snake#male#reference#notes#75
dragon#female#snake#female#reference#notes#75
dragon#male#horse#male#reference#notes#75
dragon#male#horse#female#reference#notes#75
dragon#female#horse#male#reference#notes#75
dragon#female#horse#female#reference#notes#75
dragon#male#lamb#male#reference#notes#75
dragon#male#lamb#female#reference#notes#75
dragon#female#lamb#male#reference#notes#75
dragon#female#lamb#female#reference#notes#75
dragon#male#monkey#male#reference#notes#100
dragon#male#monkey#female#reference#notes#100
dragon#female#monkey#male#reference#notes#100
dragon#female#monkey#female#reference#notes#100
dragon#male#rooster#male#reference#notes#100
dragon#male#rooster#female#reference#notes#100
dragon#female#rooster#male#reference#notes#100
dragon#female#rooster#female#reference#notes#100
dragon#male#dog#male#reference#notes#25
dragon#male#dog#female#reference#notes#25
dragon#female#dog#male#reference#notes#25
dragon#female#dog#female#reference#notes#25
dragon#male#pig#male#reference#notes#50
dragon#male#pig#female#reference#notes#50
dragon#female#pig#male#reference#notes#50
dragon#female#pig#female#reference#notes#50
snake#male#snake#male#reference#notes#75
snake#male#snake#female#reference#notes#75
snake#female#snake#female#reference#notes#75
snake#male#horse#male#reference#notes#75
snake#male#horse#female#reference#notes#75
snake#female#horse#male#reference#notes#75
snake#female#horse#female#reference#notes#75
snake#male#lamb#male#reference#notes#75
snake#male#lamb#female#reference#notes#75
snake#female#lamb#male#reference#notes#75
snake#female#lamb#female#reference#notes#75
snake#male#monkey#male#reference#notes#50
snake#male#monkey#female#reference#notes#50
snake#female#monkey#male#reference#notes#50
snake#female#monkey#female#reference#notes#50
snake#male#rooster#male#reference#notes#100
snake#male#rooster#female#reference#notes#100
snake#female#rooster#male#reference#notes#100
snake#female#rooster#female#reference#notes#100
snake#male#dog#male#reference#notes#50
snake#male#dog#female#reference#notes#50
snake#female#dog#male#reference#notes#50
snake#female#dog#female#reference#notes#50
snake#male#pig#male#reference#notes#50
snake#male#pig#female#reference#notes#50
snake#female#pig#male#reference#notes#50
snake#female#pig#female#reference#notes#50
horse#male#horse#male#reference#notes#50
horse#male#horse#female#reference#notes#50
horse#female#horse#female#reference#notes#50
horse#male#lamb#male#reference#notes#100
horse#male#lamb#female#reference#notes#100
horse#female#lamb#male#reference#notes#100
horse#female#lamb#female#reference#notes#100
horse#male#monkey#male#reference#notes#75
horse#male#monkey#female#reference#notes#75
horse#female#monkey#male#reference#notes#75
horse#female#monkey#female#reference#notes#75
horse#male#rooster#male#reference#notes#75
horse#male#rooster#female#reference#notes#75
horse#female#rooster#male#reference#notes#75
horse#female#rooster#female#reference#notes#75
horse#male#dog#male#reference#notes#100
horse#male#dog#female#reference#notes#100
horse#female#dog#male#reference#notes#100
horse#female#dog#female#reference#notes#100
horse#male#pig#male#reference#notes#75
horse#male#pig#female#reference#notes#75
horse#female#pig#male#reference#notes#75
horse#female#pig#female#reference#notes#75
lamb#male#lamb#male#reference#notes#75
lamb#male#lamb#female#reference#notes#75
lamb#female#lamb#female#reference#notes#75
lamb#male#monkey#male#reference#notes#75
lamb#male#monkey#female#reference#notes#75
lamb#female#monkey#male#reference#notes#75
lamb#female#monkey#female#reference#notes#75
lamb#male#rooster#male#reference#notes#75
lamb#male#rooster#female#reference#notes#75
lamb#female#rooster#male#reference#notes#75
lamb#female#rooster#female#reference#notes#75
lamb#male#dog#male#reference#notes#50
lamb#male#dog#female#reference#notes#50
lamb#female#dog#male#reference#notes#50
lamb#female#dog#female#reference#notes#50
lamb#male#pig#male#reference#notes#100
lamb#male#pig#female#reference#notes#100
lamb#female#pig#male#reference#notes#100
lamb#female#pig#female#reference#notes#100
monkey#male#monkey#male#reference#notes#75
monkey#male#monkey#female#reference#notes#75
monkey#female#monkey#female#reference#notes#75
monkey#male#rooster#male#reference#notes#75
monkey#male#rooster#female#reference#notes#75
monkey#female#rooster#male#reference#notes#75
monkey#female#rooster#female#reference#notes#75
monkey#male#dog#male#reference#notes#75
monkey#male#dog#female#reference#notes#75
monkey#female#dog#male#reference#notes#75
monkey#female#dog#female#reference#notes#75
monkey#male#pig#male#reference#notes#50
monkey#male#pig#female#reference#notes#50
monkey#female#pig#male#reference#notes#50
monkey#female#pig#female#reference#notes#50
rooster#male#rooster#male#reference#notes#50
rooster#male#rooster#female#reference#notes#50
rooster#female#rooster#female#reference#notes#50
rooster#male#dog#male#reference#notes#50
rooster#male#dog#female#reference#notes#50
rooster#female#dog#male#reference#notes#50
rooster#female#dog#female#reference#notes#50
rooster#male#pig#male#reference#notes#75
rooster#male#pig#female#reference#notes#75
rooster#female#pig#male#reference#notes#75
rooster#female#pig#female#reference#notes#75
dog#male#dog#male#reference#notes#75
dog#male#dog#female#reference#notes#75
dog#female#dog#female#reference#notes#75
dog#male#pig#male#reference#notes#75
dog#male#pig#female#reference#notes#75
dog#female#pig#male#reference#notes#75
dog#female#pig#female#reference#notes#75
pig#male#pig#male#reference#notes#50
pig#male#pig#female#reference#notes#50
pig#female#pig#female#reference#notes#50`;

export default txt;

// 길100
// 무난 75
// 흉 50
// 대흉 50
